### ISSUE TITLE
lotus lite adding additional version info to dial address/not respecting api version 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#10099]
when using  FULLNODE_API_INFO to remote apis like https://api.hyperspace.node.glif.io/rpc (for lotus lite), lotus is adding additional version info https://github.com/filecoin-project/lotus/blob/1791db57f67364d9e1f72715cdb59080a611d6bd/cli/util/apiinfo.go#L60

what the API provider is providing v0 API, we are also defaulting only calling GetGatewayAPI which is for v1 (GetGatewayAPIV0 is unused)

which seems to be further impact GetRawAPIMulti 

to repro 

```
export FULLNODE_API_INFO=wss://wss.hyperspace.node.glif.io/apigw/lotus/rpc/v0
/lotus daemon --lite
2023-01-23T00:34:42.059-0500    INFO    main    lotus/daemon.go:219     lotus repo: ../../../ext/.lotushyper
2023-01-23T00:34:42.065-0500    WARN    cliutil util/apiinfo.go:94      API Token not set and requested, capabilities might be limited.
ERROR: cannot dial address wss://wss.hyperspace.node.glif.io/apigw/lotus/rpc/v0/rpc/v1 for websocket: bad handshake: websocket: bad handshake

```

`wss://wss.hyperspace.node.glif.io/apigw/lotus/rpc/v0` -> ` wss://wss.hyperspace.node.glif.io/apigw/lotus/rpc/v0/rpc/v1`

**Comment by magik6k** [comment]
FULLNODE_API_INFO Shouldn’t contain the /rpc/v0 / v1 part. It’s meant to point at the root of the api endpoint.

Users shouldn’t need to specify api version used by lotus, because it’s up to lotus to decide which one it uses. Today lite mode uses v1, and some commands use v0.

If the node provider is only providing v0 api then it just means that the service can’t support lite nodes

**Comment by jennijuju** [comment]
> Users shouldn’t need to specify api version used by lotus, because it’s up to lotus to decide which one it uses. 

i think i disagree here unfortunately,i think user (node operators) should choose which API version they like to use, especially when it comes to stable vs unstable apis. The same goes to lite mode.

**Comment by jennijuju** [comment]
For example, glif provides both v0 and v1 apis for their users to chose according to their usage & stableness comfort level. They then pass that preference to lotus and lotis should not overwrite it. If FULLNODE_API_INFO is not meant for yet, then we probably should think about whether we need to repurpose it or introduce a new config - as we expect more developers coming building on filecoin and use remote API services with fvm coming.

and.. its not uncommon for [service providers to version their API according to their biz.](https://www.akana.com/blog/api-versioning)

**Comment by magik6k** [comment]
The thing is that in lite mode lotus is the API client, and we use latest (v1) api, because all internals are based on v1 interface. Supporting v0 would mean implementing a translation layer from v0->v1, and it would not be able to do everything, and just add more burden when we'll want to support more api versions.

Note that when you are running a lite node (which is a v1 gateway client), it still exposes both v1 and v0 apis

**Comment by jennijuju** [comment]
Let's parking lot on why lotus uses unstable API for production features. - we can also ask service providers feedback.
this is also definitely missing user documentation.
tho as a workaround for now application developers can set  `export FULLNODE_API_INFO=wss://wss.hyperspace.node.glif.io/apigw/lotus`

**Comment by dumikau** [comment]
Hi! :) Glif node hosting here.

Basically what we're doing with the wss.hyperspace.node.glif.io endpoint is that we check the path of all requests and if the path matches the regular expression `/apigw/lotus/(.*)` then we forward the `(.*)` part to the lotus gateway. What happens next is up to lotus gateway to decide.

**Comment by magik6k** [comment]
> tho as a workaround for now application developers can set export FULLNODE_API_INFO=wss://wss.hyperspace.node.glif.io/apigw/lotus

This isn't a workaround, this is the correct thing to do.

> Let's parking lot on why lotus uses unstable API for production features. - we can also ask service providers feedback.
this is also definitely missing user documentation.

Agree that this wasn't documented. Also worth noting that "unstable" doesn't mean that it may not work, it just meant that it can change without much notice. Which, for lotus, is fine, because we also happen to be implementing the API - so the changes are atomic. Fwiw v0 api implementation is just a thin wrapper on top of v1, and it is missing features needed by lite node.
