### ISSUE TITLE
EthGetTransactionCount ignores input

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#10357]
The blkParam argument is ignored by EthGetTransactionCount, which instead always returns nonce based on the mempool. We should:

- only call into the mempool if "pending" is supplied
- get this value from State otherwise
- consider dropping the TSK param passed to the mempool's GetNonce method

**Comment by virajbhartiya** [comment]
I’ll like to work in this. @aarshkshah1992

**Comment by virajbhartiya** [comment]
@aarshkshah1992, I'd like to share my proposed implementation for handling the "pending" block case:

```go
if blkParam.PredefinedBlock != nil && *blkParam.PredefinedBlock == "pending" {
    nonce, err := a.MpoolAPI.MpoolGetNonce(ctx, addr)
    if err != nil {
        return ethtypes.EthUint64(0), xerrors.Errorf("failed to get nonce from mpool: %w", err)
    }
    return ethtypes.EthUint64(nonce), nil
}
```
1. It checks if `blkParam.PredefinedBlock` is not nil and specifically set to "pending".
2. If the condition is met, it retrieves the nonce from the mempool using `MpoolGetNonce`.
3. The mempool is only queried in this specific "pending" case, optimizing performance for other scenarios.

**Comment by virajbhartiya** [comment]
I am a bit new to this as for my understanding of `mempool` is that it is a temporary holding area for transactions that have been submitted to the network but haven't yet been included in a block. The mempool keeps track of the expected next nonce for each account based on pending transactions. When pending block is encountered,  it queries  the mempool for the latest nonce to get the most up-to-date state. Since querying the mempool can be more resource-intensive than querying the confirmed blockchain state, that is why we want to do it only for  "pending" block requests.
