### ISSUE TITLE
eth_getTransactionReceipt  panic

### ISSUE THREAD

**Issue by zhp1254** [filecoin-project/lotus#10471]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus Ethereum RPC
- [ ] lotus FVM - Lotus FVM interactions
- [ ] FEVM tooling
- [ ] Other

### Lotus Version

```text
https://api.hyperspace.node.glif.io/rpc/v1
```

### Describe the Bug

fatal error calling 'Filecoin.EthGetTransactionReceipt': panic in rpc method 'Filecoin.EthGetTransactionReceipt': division by zero, txid:0x36b04daa4b871973b6ee40d322ef08008ad49fe61f418cf10df57a97d049a498

### Tooling

```text
import "github.com/ethereum/go-ethereum/ethclient"
```

### Configuration Options

```text
ethclient.client.TransactionReceipt(context.Background(), common.HexToHash(txid))
```

**Comment by magik6k** [comment]
Can you provide the full panic output from lotus node logs?

**Comment by raulk** [comment]
I was unable to reproduce the failure:

```
⟩ curl --silent --url 'https://api.hyperspace.node.glif.io/rpc/v1' \
          -X POST \
          -d '{"method":"eth_getTransactionReceipt","params":["0x36b04daa4b871973b6ee40d322ef08008ad49fe61f418cf10df57a97d049a498"],"id":1,"jsonrpc":"2.0"}' \
          -H "Content-Type: application/json"
{"jsonrpc":"2.0","result":null,"id":1}
```

This refers to a message that should've never been included on chain due to having insufficient gas to cover chain inclusion, but was included only in Hyperspace due to a mismatch between the Lotus and the FVM gas pricelists:

https://hyperspace.filfox.info/en/message/0x36b04daa4b871973b6ee40d322ef08008ad49fe61f418cf10df57a97d049a498

![image](https://user-images.githubusercontent.com/1101242/224972996-b48bce46-2fdd-40fc-8bd9-54210cd64176.png)

This will be solved in the future.

@zhp1254 please use `eth_estimateGas` to estimate gas instead of setting an arbitrary number.
