### ISSUE TITLE
Eth RPC: Address performance of EthSendRawTransaction

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/lotus#10540]
We identified `EthSendRawTransaction` as one of the hotspots on Glif production nodes. The goal of this issue is to investigate the reason and fix it.

![image (2)](https://user-images.githubusercontent.com/17002645/226992507-119f82c0-3431-4fc3-9f21-df381ede67b6.png)

**Comment by maciejwitowski** [comment]
Update: after current fixes, dashboards show it is still occasionally slow.

**Comment by fridrik01** [comment]
What would be the best way to test this method locally on my lotus node, especially when I want to stress test it?  cc: @Stebalien

**Comment by raulk** [comment]
Would sending a message with a nonce gap (so that it always sits in the mempool), and then stressing by sending messages incrementing the gas premium 11% over the previous message, be reasonable to way to stress test this? Not sure if the mpool executes messages with a nonce gap though; if it doesn't, it won't exercise contention areas.

**Comment by Stebalien** [comment]
We've added a significant amount of parallelism to the FVM itself which should have fixed this issue.
