### ISSUE TITLE
Seeing redeclaring storage tasks several times every day

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#10901]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
Daemon:  1.23.1-rc2+mainnet+git.5a1738c9b+api1.5.0
Local: lotus-miner version 1.23.1-rc2+mainnet+git.5a1738c9b
```

### Repro Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

### Describe the Bug

Since Lotus v1.23.x upgrade I am seeing storage repo redeclared several times per day. This does not seem to affect the operation but is annoying. My storage repo is directly attached to the lotus-miner (via SATA cables on same box).

When I first saw this I asked either Reiers or Phi-rjan and he saw the same issue.

### Logging Information

```text
2023-05-22T13:51:12.915Z	INFO	stores	paths/index.go:181	New sector storage: d8cfac01-4999-45d5-8231-8aa9423224e2

2023-05-22T13:51:12.919Z	WARN	stores	paths/index.go:369	sector {1278 1072} redeclared in d8cfac01-4999-45d5-8231-8aa9423224e2
2023-05-22T13:51:12.919Z	WARN	stores	paths/index.go:369	sector {1278 1076} redeclared in d8cfac01-4999-45d5-8231-8aa9423224e2
[And thousands more of these lines, one per sector]
2023-05-22T13:51:13.217Z	WARN	stores	paths/index.go:369	sector {1278 997} redeclared in d8cfac01-4999-45d5-8231-8aa9423224e2
2023-05-22T13:51:13.217Z	WARN	stores	paths/index.go:369	sector {1278 998} redeclared in d8cfac01-4999-45d5-8231-8aa9423224e2
2023-05-22T13:51:13.217Z	WARN	stores	paths/index.go:369	sector {1278 999} redeclared in d8cfac01-4999-45d5-8231-8aa9423224e2


2023-05-22T13:51:13.217Z	INFO	stores	paths/index.go:181	New sector storage: f2b17c6d-0800-49be-801d-b86f95958a3a
[The one above is the remote AP-Worker]
```

**Comment by stuberman** [comment]
Also seeing this in the Boostd logs at the same time
2023-05-22T13:51:12.741Z        INFO    unsmgr  indexprovider/unsealedstatemanager.go:77        checking for sector state updates
2023-05-22T13:51:12.742Z        INFO    unsmgr  indexprovider/unsealedstatemanager.go:81        redeclaring storage

**Comment by rjan90** [comment]
Hey @stuberman! 

This is due to the addition of an index integrity check added in [Boost 1.7.0](https://github.com/filecoin-project/boost/releases/tag/v1.7.0). The storage list api that Boost relies on unfortunately doesn’t automatically update removed sectors or removed unsealed copies, so they ask lotus-miner to update the list via the redeclare storage api, which should be a fairly light call.

you can configure how often this occurs, and you can also shut off the redeclare if you would prefer to handle that manually. Here are the boost config defaults:

```
Storage.StorageListRefreshDuration = "1h0m0s"
Storage.RedeclareOnStorageListRefresh = true
```

Bumping this higher will make it happen less often, or if you want to manually handle it via your own scripts you can change RedeclareOnStorageListRefresh to false, and run lotus-miner storage redeclare on occasion when unsealed or sealed sectors are removed.

Longer term we have been looking at making these updates automatic when sealed or unsealed sectors are removed. In the meantime, maybe we should just change the log level from `WARN` to `INFO`, so it does not sound so scary? Would love to hear your inputs

**Comment by stuberman** [comment]
Thanks, this is good info and should be well documented. I do think that the log level should be much lower, such as debug if it is expected and not important to track.
