### ISSUE TITLE
Feat: deps: LotusTasks package for HA

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11026]
**User Story**
Lotus Pipelines want a robust, distributed, greedy, Highly-Available task scheduler to manage task adding, assignment, retry, completion, and removal [see SturdyPoSt's HA WindowPoSt](https://docs.google.com/document/d/1lPe-6HdVe_oU0mD29f9Zi4233_xhSbyiXxM_6zXG4hY/edit?pli=1).

**Acceptance Criteria**
A package lotustasks that:
- has a New(config) that sets up given task handlers, starts listeners for external, starts a db poller, implements a greedy work sharing mechanism with backoff properties, and manages in-DB task state including ownership and done-ness.

**Tech Scope**
The lotustasks portion of [SturdyPoSt's HA WindowPoSt](https://docs.google.com/document/d/1lPe-6HdVe_oU0mD29f9Zi4233_xhSbyiXxM_6zXG4hY/edit?pli=1)

**Test Plan**
New integration tests that operate a variety of task systems and ensure tasks can be created in one worker, scheduled and completed in another, and complete after a virtual restart while not getting picked-up elsewhere.

**Comment by jennijuju** [comment]
> Lotus Devs want a distributed, greedy task scheduler to enable Highly-Availability of various tasks [see SturdyPoSt's HA WindowPoSt](https://docs.google.com/document/d/1lPe-6HdVe_oU0mD29f9Zi4233_xhSbyiXxM_6zXG4hY/edit?pli=1).

What does ACTUAL lotus miner user get out of this?

**Comment by jennijuju** [comment]
> > Lotus Devs want a distributed, greedy task scheduler to enable Highly-Availability of various tasks [see SturdyPoSt's HA WindowPoSt](https://docs.google.com/document/d/1lPe-6HdVe_oU0mD29f9Zi4233_xhSbyiXxM_6zXG4hY/edit?pli=1).
> 
> What does ACTUAL lotus miner user get out of this?

I think we should simply skip the user story for this one give it is a sub task for delivering HA post, and thus they share the user story.

**Comment by scotthconner** [comment]
The user story and scope should be commiserate with something tangible.

"As a Lotus daemon, I can spawn requisite LotusTasks to properly support my windowPost demands."

This layered cake would include:
* the lotus tasks package and interface for registering lotus tasks available for work to describe a particular work for windowPost.
* The glue code that determines when the daemon should put work into the queue. 
* A demonstration that work gets added to the queue in a similar fashion as the legacy scheduler could or would. (That required posts are tasked sufficiently in advance of needing it)

This is marginally useful - the lotus daemon would schedule tasks into a working DB that aren't used for anything. But still, its an atomic integration that covers a complete portion of a tasks lifecylce - its creation.

**Comment by jennijuju** [comment]
> the lotus daemon would schedule tasks into a working DB that aren't used for anything

@snadrus can you confirm this is right? From my understanding, the plan is to only treating the daemon as the source of the worker/miner's chain watcher, and worker/miner nodes with idle resources are the ones registering tasks to the DB?

**Comment by jennijuju** [comment]
Process wise: I think while whats mentioned above make sense,  idk if they can just belong to acceptance criteria and technical breakdown.
(re: user story, my thought process is if we are not doing HA post, will we still want this task for “post demands”?  - likely no. Thats why  I dont think its necessary to have a separate user story.)

**Comment by scotthconner** [comment]
Whether or not the daemon itself is responsible for the task generation, or the workers themselves understand how to "Recognize" when tasks should be made available, while a design question ("who is responsible for determining a task needs to be done? Is it the composition of the work or a daemon, there are trade-offs etc") that is important, to me is generally a detail when it comes to organizing the work.

My main issue with the way this is organized is the deliverable is a package that no one is currently using for anything useful. My post above was to attempt to clarify an example how you could re-cut it so that it did at least a portion of what was deemed useful for tasks - creating and storing them.

If the truth is the workers scan to identify work *they* can pick up - great - good encapsulation, seems like a robust design choice. Then the story would be that a specific type of worker could register tasks it wants to do.

If that was the case, the "ACTUAL" use a lotus miner user would get out of it is the ability to spawn a window post worker that registered tasks in yugaDB it thinks it should do. Its a complete use case for a portion of the task lifecycle.

**Comment by arajasek** [comment]
> Process wise: I think while whats mentioned above make sense, idk why not have them just belong to acceptance criteria and technical breakdown. (re: user story, my thought process is if we are not doing HA post, will we still want this task for “post demands”? - likely no. Thats why I dont think its necessary to have a separate user story.)

Drive-by opinion: I think it's nice if each cake is standalone, and has its own user story. I think that will lead to better design when building individual components, instead of producing a component that's very targeted to one specific use-case we have in mind (which we risk by saying "the user story is that this is needed for SturdyPoSt").

I actually really like the User Story in the OP -- I think it makes sense to describe the "user" as Lotus Devs for this work item. We could probably add a bit more motivation for why we might want this, and then point to the one very concrete example we have.

**Comment by jennijuju** [comment]
moving this issue to backlog from Sprint 2 in favour of a higher priority toward #10970

**Comment by rjan90** [comment]
Closed by: https://github.com/filecoin-project/lotus/pull/11165
