### ISSUE TITLE
State Invariant Checker Lotus Task

### ISSUE THREAD

**Issue by snissn** [filecoin-project/lotus#11023]
## User Story

I want to know what is happening with filecoin state, and see the output of the state invariant checker. I also want to see diffs to show changes to the output of the checker.

## Acceptance Criteria

```[tasklist]
### Deliverables
- [x] A cron job that runs state invariant check against the latest snapshot weekly, on Sunday.
- [x] A slack alert integration if there are any unexpected state invariants failure outputs.
```

## Technical Breakdown 
```[tasklist]
- [x] Cron file that runs the task weekly
- [x] Slack ping if diff is not empty
```

**Comment by jennijuju** [comment]
I want to learn more about what can we gain from serving this the state invariant checker output on the website. Or do we only need to have the save as a backup thats available for lookup when getting an alert?

**Comment by arajasek** [comment]
> I want to learn more about what can we gain from serving this the state invariant checker output on the website. Or do we only need to have the save as a backup thats available for lookup when getting an alert?

I think this is a nice-to-have. It will be good for when we have longer-running problems, because it gives us some insight into how things might be getting better / worse over time.

However, I think we really should get to a place where we have no broken invariants -- once we do so, this basically screams bloody murder if we have a single break (it becomes a binary alert). As a result, hosting these on some website may not be too useful.

**Comment by snissn** [comment]
defer on web server

**Comment by snissn** [comment]
done! Project lives here: https://github.com/FILCAT/lotus-ec2-tools and pings slack with updates
