### ISSUE TITLE
[Shipped] Lotus Client Release v1.27.1

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#12073]
## 🚢 Estimated shipping date

- RC1: June 11th, 2024
- Stable: June 24th, 2024

## ✅ Release Checklist
- [x] Fork a new branch (`release/vX.Y.Z`) from `master` and make any further release related changes to this branch. If any "non-trivial" changes get added to the release, uncheck all the checkboxes and return to this stage.
- [x] Bump the version in `build/version.go` in the `master` branch to `vX.Y.(Z+1)-dev` (bump from feature release) or `vX.(Y+1).0-dev` (bump from mandatory release). Run make gen and make docsgen-cli before committing changes
https://github.com/filecoin-project/lotus/pull/12074

**Prepping an RC**:

- [x] version string in `build/version.go` needs to be updated to end with '-rcX' (in the `release/vX.Y.Z` branch)
- [x] run `make gen && make docsgen-cli`
- [x] Generate changelog using the script at scripts/mkreleaselog
- [x] Add contents of generated text to lotus/CHANGELOG.md in addition to other details
- [x] Commit using PR 
- [x] tag commit with `vX.Y.Z-rcN`
- [x] cut a pre-release [here](https://github.com/filecoin-project/lotus/releases/new?prerelease=true)

**Stable Release**
  - [x] Final preparation
    - [ ] Verify that version string in [`version.go`](https://github.com/filecoin-project/lotus/blob/master/build/version.go) has been updated.
    - [ ] Verify that codegen is up to date (`make gen && make docsgen-cli`)
    - [ ] Ensure that [CHANGELOG.md](https://github.com/filecoin-project/lotus/blob/master/CHANGELOG.md) is up to date
    - [ ] Merge `release-vX.Y.Z` into the `releases` branch.
    - [ ] Tag this merge commit (on the `releases` branch) with `vX.Y.Z`
    - [x] Cut the release [here](https://github.com/filecoin-project/lotus/releases/new?prerelease=false&target=releases).

**Post-Release**
  - [x] Merge the `releases` branch back into `master`, ignoring the changes to `version.go` (keep the `-dev` version from master). Do NOT delete the `releases` branch when doing so!
  - [ ] Update [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) with any improvements determined from this latest release iteration.
  - [ ] Create an issue using [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) for the _next_ release.

**Comment by rjan90** [comment]
Writing down steps taken here, and some timings so we can get a baseline:

- Copy/Paste issue template
**1 m**

- Fork a new branch (release/vX.Y.Z) from master and make any further release related changes to this branch.
**1 m**

- Bump the version in build/version.go in the master branch to vX.Y.(Z+1)-dev (bump from feature release) or vX.(Y+1).0-dev (bump from mandatory release). Run make gen and make docsgen-cli before committing changes in a PR: https://github.com/filecoin-project/lotus/pull/12074
**5 m**

**Comment by BigLep** [comment]
@rjan90 :
1. Thanks for creating the issue
2. I like your idea of recording every step taken and how long it takes.  That will be good for seeing the opportunity here to improve and how much the improvements are actually helping.  Good stuff

Not to self: once I get part of lotus-contributors team, I will:
1. Pin the issue
2. Add to FilOz board
(if this isn't done already)

**Comment by rjan90** [comment]
Adding time I used for the `Post-Release` when finishing it for v1.27.0: https://github.com/filecoin-project/lotus/issues/11938. PR here: https://github.com/filecoin-project/lotus/pull/12076

- Merge the releases branch back into master, ignoring the changes to version.go (keep the -dev version from master). Do NOT delete the releases branch when doing so!

**25 minutes**

**Notes**
High variance in time consumption depending on how many conflicts that needs to be resolved. Sometimes I probably spend 2x the amount, others 1/5 of the amount of the time measured.

**Comment by rjan90** [comment]
### Timings for RC2-parts:

- Writing more on the changelog, going through PRs landed since RC1 and adding backports:
**20m**

- run `make gen` && `make docsgen-cli`
**5m**

**Comment by BigLep** [comment]
@aarshkshah1992 : I didn't sync with @rjan90 on this release (I've only been discussing 1.28.0).  I assume you're going to handle this.  Is it clear to you when (date and conditions) to make the final release?  I'm bringing this up because the 1.28.0 release (https://github.com/filecoin-project/lotus/issues/12109 ) will branch from this.

**Comment by jennijuju** [comment]
@BigLep oops sorry just saw your last comment - i will handle this one!

**Comment by BigLep** [comment]
Per 2024-06-25 verbal conversation, this is complete: https://github.com/filecoin-project/lotus/releases/tag/v1.27.1

**Comment by rvagg** [comment]
_(Noting this here because I've been asked twice now and there may be others)._

This release contains a migration in the events database, full details of this are in https://github.com/filecoin-project/lotus/pull/11952

The events database is not turned on in the default Lotus configuration, you have to turn one of a few things on in order for it to be running. If your Lotus configuration has at least one of the following options then you have the database on:

* `Events.DisableHistoricFilterAPI=false`
* `Fevm.Events.DisableHistoricFilterAPI=false`

You can also check for yourself by looking at your lotus repo directory: if there is a `sqlite/events.db` file that has been recently modified then you have it turned on.

For users who are operating the events database and find themselves wanting to downgrade from this release to v1.27.0, this is possible, but it requires some manual work. This particular migration is (roughly) idempotent, so going back and forth through the migration should be non-destructive and should not cause errors if done correctly. The main problem is that we store a schema version in the events database once the migration is performed so we know it doesn't need to be done again. This version needs to be wound back to the previous version when starting with an older version of Lous. If you attempt to un an older version of Lotus with a migrated database then you'll get an error, something like: `invalid database version: got 5, expected 4`.

## To downgrade

_**NOTE: this instructions are specific to the migration in https://github.com/filecoin-project/lotus/pull/11952 (in Lotus v1.27.1) and only works because the schema of the database did not change.** If you require help downgrading other versions, please ask, there _may_ or may not be simply ways to achieve it._

1. [Install SQLite 3](https://www.sqlite.org/download.html) (should be available in most Linux package managers as `sqlite3`) so that we have the `sqlite3` CLI tool.
1. Stop your Lotus v1.27.1 daemon; waiting until it has fully shut down
2. (As the user running the `lotus` daemon, or with `sudo`) Run `sqlite3 /path/to/lotus/repo/sqlite/events.db` (your Lotus repo may simply be `~/.lotus/`).
3. Copy this SQL into the CLI tool: `DELETE FROM _meta WHERE version = 5;` and press enter.
4. Exit with `.exit`
5. Start your Lotus **v1.27.0** daemon. Watch the logs, checking for mentions of "event index" or "database".

As soon as you make the switch from v1.27.0 to v1.27.1 (or later), the migration will be re-run and the version `5` will be re-inserted.

## Additional notes

Please be aware that v1.27.1 contains a fix for this Ethereum API incompatibility bug: https://github.com/filecoin-project/lotus/issues/11630, downgrading back to v1.27.0 will lose the fix _and_ will also give you different event indexes to a non-migrated v1.27.0 (and previous) node. Events prior to your downgrade will be properly indexed (which v1.27.0 and prior won't have), but events after the downgrade will be improperly indexed. If you don't have an application that depends on indexes to be correct as per the Ethereum API then this is unlikely a concern. When proceeding past this migration in a future upgrade (to v1.27.1 or some future version), your indexes should be fixed again as all historical events are re-indexed.

**Comment by jennijuju** [comment]
@rvagg should we add this to release note?

**Comment by rvagg** [comment]
@jennijuju yeah, I can do that, but I also put an additional caveat just now in the middle of my text, I don't want to give the impression this is a guaranteed solution. Migrations are normally intended to go one way, this one just happens to be fairly simple.
