### ISSUE TITLE
[lotus-seal-worker] ctrl-C doesn't kill worker when it is running param-fetch

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/lotus#1209]
**Describe the bug**
After starting the `lotus-seal-work`, it started downloading the proof params, I attempted to stop it at this point with CTRL-C but it had no effect and it continued to download the params.

I ended up using `kill -9 <pid>` to get it to stop. 

**To Reproduce**
1. Run `lotus-seal-worker run`
2. Hit CTRL-C

**Expected behavior**
`lotus-seal-worker` should exit.

**Version (run `lotus --version`):**
lotus version 0.2.7+git9935e3ac

**Comment by laser** [comment]
Some notes:

1. The `lotus-seal-worker run` command uses the [`ReqContext` function](https://github.com/filecoin-project/lotus/blob/master/cmd/lotus-seal-worker/main.go#L124).
1. The `ReqContext` function registers returns a new context that is cancelled when the current process receives SIGHUP, SIGINT, or SIGTERM.
1. The context returned from `ReqContext` isn't passed to the `paramfetch.GetParams` function (this function doesn't accept a context). Because of this, cancelling that context (by way of sending a SIGTERM from console) doesn't terminate the `paramfetch.GetParams` call.

**Comment by laser** [comment]
Once #1933 merges, this issue can be closed.
