### ISSUE TITLE
Update StateMinerInitialPledgeCollateral method to be DDO aware

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/lotus#12369]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
NA
```

### Repro Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

### Describe the Bug

Method StateMinerInitialPledgeCollateral was used to calculate the initial collateral to be send via ProveCommit1 and ProveCommit2 messages for the deal sectors. Post DDO, this calculation seem off and collateral is too low. This results in collateral being deducted from miner balance.

I would request the team to fix the calculation to account for DDO sectors and add additional method to allow calculation for pledge for snap-deals as well. This can either be an additional method or use the same one.

### Logging Information

```text
NA
```

**Comment by rjan90** [comment]
We need to understand/investigate if DDO has had any impact on the `StateMinerInitialPledgeCollateral` method. @rvagg Is this something you could spend some time on when you have availability,

**Comment by rvagg** [comment]
Copying my comment from [here](https://github.com/filecoin-project/lotus/pull/12384#issuecomment-2290771193) in hope of getting some engagement:

As per https://github.com/filecoin-project/builtin-actors/issues/1573 I think we can simplify the API even further; here are the options as I see them:

* `StateMinerInitialPledgeForSector(size, duration, pieceManifests)` so you can use it arbitrarily to do the calculation with arbitrary params, or
* `StateMinerInitialPledgeForSector(sectorManifest)` so you can load the precommit and figure out size and duration from that, and potentially do some checking on the claims to confirm if they could be successfully activated (provider, term, etc.).
* `StateMinerInitialPledgeForSector(duration, size, verifiedSize)` because ultimately those are the only inputs we need, the rest comes from the power actor.
