### ISSUE TITLE
Support eth_getBlockReceipts

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/lotus#12429]
I _think_ the output of this is the same as `eth_getTransactionReceipts` but you query for the block number instead of transaction hash and the result is just an array with all of the `eth_getTransactionReceipts` results.

This is an efficient way to get all details of a tipset rather than querying for all messages and constructing it yourself. Just need to be careful about doing proper de-duplication.

**Comment by virajbhartiya** [comment]
I'd Like to work on this

**Comment by rjan90** [comment]
> I'd Like to work on this

Awesome, I will assign this ticket to you then @virajbhartiya

**Comment by virajbhartiya** [comment]
Hey, @rjan90, so just to be clear, we have to implement a function `eth_getBlockReceipts` that will allow clients to retrieve all transaction receipts from a specific block. So instead of querying for each transaction using`eth_getTransactionReceipt`, we query for the block, and it would return an array of all transaction receipts from that block?

**Comment by rvagg** [comment]
@virajbhartiya yes, but please do a bit of research on the various forms of Ethereum documentation out there to confirm that `eth_getBlockReceipts` is precisely that. That's my understanding from a brief bit of research but it would be good to confirm.

**Comment by virajbhartiya** [comment]
@rvagg I have submitted a PR, can you please give it a look

**Comment by virajbhartiya** [comment]
Hey @rvagg @rjan90 im having some trouble passing a few tests, could you please help me out with those
