### ISSUE TITLE
[SEV1] Nodes stop syncing due to "failed to verify beacon".

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#12467]
This issue is capturing the investigation and communication about the network sync issue that occurred for some Lotus nodes on 2024-09-16 16:35 UTC (https://status.filecoin.io/#subscribe-modal-s11bzdg62qcb).

**Comment by momack2** [comment]
We are investigating a possible issue with 1.28.2 and beyond versions. A number of SPs are indicating success in downgrading to lotus 1.28.1 and below. We have been able to reproduce regaining sync through downgrading to 1.28.1. If you're experiencing this issue, we recommend trying to downgrade to 1.28.1 or before in the meantime, while lotus eng diagnose the specific root cause.

**Comment by BigLep** [comment]
We have identified the issue and will be publishing a Lotus node v1.28.3 and v1.29.1 that addresses the issue.  We'll post here as soon the releases are ready for consumption.  

We'll update the issue after about the root cause.

**Comment by rvagg** [comment]
* master: https://github.com/filecoin-project/lotus/pull/12469
* v1.28.3: https://github.com/filecoin-project/lotus/pull/12468
* v1.29.1: wip

**Comment by BigLep** [comment]
To be clear, as soon as the patches are released, we recommend all users either update to v1.28.3 or v1.29.1.  With these upcoming patches, a user only needs to upgrade.  **One does NOT need to adjust any config flags like`EnableEthRPC`.***

**Comment by BigLep** [comment]
Patches have been released:
v1.28.3: https://github.com/filecoin-project/lotus/releases/tag/v1.28.3
v1.29.1: https://github.com/filecoin-project/lotus/releases/tag/v1.29.1

Per before, all users are encouraged to upgrade ASAP and no updates are needed to one's config.

**Comment by BigLep** [comment]
Resolving this issue since patches have been released that address the issue. 

(A separate issue has been created to properly fix this rather than rely on a go mod replace: https://github.com/filecoin-project/lotus/issues/12472 )

**Comment by joshdougall** [comment]
Hi all, I just wanted to post an update around the ChainSafe snapshot service for mainnet and calibnet. We have two Forest nodes running, that export snapshots for both networks. To validate these snapshots, they are imported into a Lotus node running v1.28.2, and once synced successfully the snapshots are made available at `https://forest-archive.chainsafe.dev/list/[mainnet/calibnet]/latest`.

The validation component was failing due to running Lotus v1.28.2, so we downgraded to v1.28.1 temporarily. There is a small gap in our snapshot archive due to this change, but the snapshot following the downgrade contains all of the blocks since the previous snapshot. We will roll out v1.28.3 shortly, but our snapshot service remained functional during the incident.
