### ISSUE TITLE
TestNet/3 Crash: when verfiy epost proof

### ISSUE THREAD

**Issue by GFZRZK** [filecoin-project/lotus#1514]
memory allocation of 139685494036720 bytes failedSIGABRT: abort
PC=0x7f0b605692a7 m=25 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f0b605692a7
stack: frame={sp:0x7f0b2cbd6468, fp:0x0} stack=[0x7f0b2c3d6f28,0x7f0b2cbd6b28)
00007f0b2cbd6368:  91f3fec9da1d2494  0000000000000000 
00007f0b2cbd6378:  00007f0b6060cd29  0000000000000000 
00007f0b2cbd6388:  000000000191e8d1  0000000000000001 
00007f0b2cbd6398:  0000000002f9d2e0  0000000000000000 
00007f0b2cbd63a8:  000000000000000d  0000000000000000 
00007f0b2cbd63b8:  00007f0b2cbd64c8  0000000000000001 
00007f0b2cbd63c8:  0000000002f9d2e0  00007f0b2cbd6428 
00007f0b2cbd63d8:  00007f0b2cbd6548  0000000000000000 
00007f0b2cbd63e8:  000000000191ed0b  000000000002b650 
00007f0b2cbd63f8:  00007f0a04000020  00007f0a0404f903 
00007f0b2cbd6408:  3435383639333190  0000000000000010 
00007f0b2cbd6418:  000000000195e5a9  0000000000000002 
00007f0b2cbd6428:  0000000000000000  0000000100000000 
00007f0b2cbd6438:  00007f0b104098f0  0000000000000000 
00007f0b2cbd6448:  00007f0b104b37c0  0000000000000020 
00007f0b2cbd6458:  00007f0b104b37d8  00007f0b1007bb60 
00007f0b2cbd6468: <00007f0b6056a688  0000000000000020 
00007f0b2cbd6478:  0000000000000000  0000000000000000 
00007f0b2cbd6488:  0000000000000000  0000000000000000 
00007f0b2cbd6498:  0000000000000000  0000000000000000 
00007f0b2cbd64a8:  0000000000000000  0000000000000000 
00007f0b2cbd64b8:  0000000000000000  0000000000000000 
00007f0b2cbd64c8:  0000000000000000  0000000000000000 
00007f0b2cbd64d8:  0000000000000000  0000000000000000 
00007f0b2cbd64e8:  0000000000000000  0000000000000000 
00007f0b2cbd64f8:  00007f0b104098f0  00007f0b2cbd6548 
00007f0b2cbd6508:  0000000000000001  00007f0b104098f0 
00007f0b2cbd6518:  00007f0b104b37d8  00007f0b1007bb60 
00007f0b2cbd6528:  000000000192e497  fffffffffffff000 
00007f0b2cbd6538:  00007f0b1040a000  00007f0b104098f0 
00007f0b2cbd6548:  00007f0b2cbd6540  000000000196be90 
00007f0b2cbd6558:  000000001fc2c403  91f3fec91fc2c48c 
runtime: unknown pc 0x7f0b605692a7
stack: frame={sp:0x7f0b2cbd6468, fp:0x0} stack=[0x7f0b2c3d6f28,0x7f0b2cbd6b28)
00007f0b2cbd6368:  91f3fec9da1d2494  0000000000000000 
00007f0b2cbd6378:  00007f0b6060cd29  0000000000000000 
00007f0b2cbd6388:  000000000191e8d1  0000000000000001 
00007f0b2cbd6398:  0000000002f9d2e0  0000000000000000 
00007f0b2cbd63a8:  000000000000000d  0000000000000000 
00007f0b2cbd63b8:  00007f0b2cbd64c8  0000000000000001 
00007f0b2cbd63c8:  0000000002f9d2e0  00007f0b2cbd6428 
00007f0b2cbd63d8:  00007f0b2cbd6548  0000000000000000 
00007f0b2cbd63e8:  000000000191ed0b  000000000002b650 
00007f0b2cbd63f8:  00007f0a04000020  00007f0a0404f903 
00007f0b2cbd6408:  3435383639333190  0000000000000010 
00007f0b2cbd6418:  000000000195e5a9  0000000000000002 
00007f0b2cbd6428:  0000000000000000  0000000100000000 
00007f0b2cbd6438:  00007f0b104098f0  0000000000000000 
00007f0b2cbd6448:  00007f0b104b37c0  0000000000000020 
00007f0b2cbd6458:  00007f0b104b37d8  00007f0b1007bb60 
00007f0b2cbd6468: <00007f0b6056a688  0000000000000020 
00007f0b2cbd6478:  0000000000000000  0000000000000000 
00007f0b2cbd6488:  0000000000000000  0000000000000000 
00007f0b2cbd6498:  0000000000000000  0000000000000000 
00007f0b2cbd64a8:  0000000000000000  0000000000000000 
00007f0b2cbd64b8:  0000000000000000  0000000000000000 
00007f0b2cbd64c8:  0000000000000000  0000000000000000 
00007f0b2cbd64d8:  0000000000000000  0000000000000000 
00007f0b2cbd64e8:  0000000000000000  0000000000000000 
00007f0b2cbd64f8:  00007f0b104098f0  00007f0b2cbd6548 
00007f0b2cbd6508:  0000000000000001  00007f0b104098f0 
00007f0b2cbd6518:  00007f0b104b37d8  00007f0b1007bb60 
00007f0b2cbd6528:  000000000192e497  fffffffffffff000 
00007f0b2cbd6538:  00007f0b1040a000  00007f0b104098f0 
00007f0b2cbd6548:  00007f0b2cbd6540  000000000196be90 
00007f0b2cbd6558:  000000001fc2c403  91f3fec91fc2c48c 

goroutine 20781590 [syscall]:
runtime.cgocall(0x11e12e0, 0xc01a2655e0, 0x1b87d00)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc01a265588 sp=0xc01a265550 pc=0x50fb7b
github.com/filecoin-project/filecoin-ffi/generated._Cfunc_fil_verify_post(0x67f278b32ef68a36, 0x6739d461c0203ab8, 0x4850e61eef298b62, 0xa7538abe71a191, 0xc45, 0x7f0b107dd900, 0x132b8, 0x7f0b104b37c0, 0x1, 0x7f0b100ab5a0, ...)
	_cgo_gotypes.go:1657 +0x51 fp=0xc01a2655e0 sp=0xc01a265588 pc=0xb251f1
github.com/filecoin-project/filecoin-ffi/generated.FilVerifyPost.func1(0x67f278b32ef68a36, 0x6739d461c0203ab8, 0x4850e61eef298b62, 0xa7538abe71a191, 0xc45, 0x7f0b107dd900, 0x132b8, 0x7f0b104b37c0, 0x1, 0x7f0b100ab5a0, ...)
	/root/lotus/extern/filecoin-ffi/generated/generated.go:639 +0x130 fp=0xc01a2656b0 sp=0xc01a2655e0 pc=0xb38bf0
github.com/filecoin-project/filecoin-ffi/generated.FilVerifyPost(0x67f278b32ef68a36, 0x6739d461c0203ab8, 0x4850e61eef298b62, 0xa7538abe71a191, 0x0, 0x0, 0x0, 0xc45, 0xc097c46000, 0x132b8, ...)
	/root/lotus/extern/filecoin-ffi/generated/generated.go:639 +0x20e fp=0xc01a2657a0 sp=0xc01a2656b0 pc=0xb376ce
github.com/filecoin-project/filecoin-ffi.VerifyPoSt(0xc04b032f80, 0x20, 0x20, 0xc04c566360, 0x1, 0x1, 0xc0270813a0, 0x1, 0x1, 0xc092844000, ...)
	/root/lotus/extern/filecoin-ffi/proofs.go:78 +0x323 fp=0xc01a2659b8 sp=0xc01a2657a0 pc=0xb414f3
github.com/filecoin-project/sector-storage/ffiwrapper.verifyPost(0x21935c0, 0xc054f251d0, 0xc04b032f80, 0x20, 0x20, 0xc04c566360, 0x1, 0x1, 0xc0270813a0, 0x1, ...)
	/root/goProject/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200327233338-c4b928d44163/ffiwrapper/verifier_cgo.go:142 +0xfc fp=0xc01a265a88 sp=0xc01a2659b8 pc=0xb7d4dc
github.com/filecoin-project/sector-storage/ffiwrapper.proofVerifier.VerifyElectionPost(...)
	/root/goProject/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200327233338-c4b928d44163/ffiwrapper/verifier_cgo.go:129
github.com/filecoin-project/lotus/chain.(*Syncer).VerifyElectionPoStProof(0xc0002d8070, 0x21935c0, 0xc054f251d0, 0xc0251b68c0, 0xc01daa8ac0, 0x31, 0x57cae4, 0x53b0aa)
	/root/lotus/chain/sync.go:867 +0xc94 fp=0xc01a265f10 sp=0xc01a265a88 pc=0xe93ed4
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6(0xc0600b8f80, 0x8)
	/root/lotus/chain/sync.go:736 +0x5b fp=0xc01a265f70 sp=0xc01a265f10 pc=0xe9f1cb
github.com/Gurpartap/async.Err.func1(0xc04d0cea80, 0xc04dc70040, 0xc031556270)
	/root/goProject/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:29 +0x5b fp=0xc01a265fc8 sp=0xc01a265f70 pc=0xe6c47b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc01a265fd0 sp=0xc01a265fc8 pc=0x56c4f1
created by github.com/Gurpartap/async.Err
	/root/goProject/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:27 +0x8a
I think there should be some wrong operation with goroutine and bugs in rust-fil-proofs or any other place since once got a bad block, the program would crash and I can't chase the chain normally, hope you can fix it soon

**Comment by cerasusland** [comment]
Actually I have ever got the same panic problem, maybe bad pointer in cgo (filecoin-ffi) , but I cannot figure it out, hope could someone fix it.

**Comment by whyrusleeping** [comment]
This code has been replaced, and has experienced many improvements. Please reopen an issue if this happens again

**Comment by btcioner** [comment]
**Describe the bug**
When i use bench, unseal

**To Reproduce**
Steps to reproduce the behavior:
1. Run './bench'
2. See error
2020-06-24T00:27:29.126 INFO filcrypto::proofs::api > unseal_range: start
2020-06-24T00:27:38.263 INFO storage_proofs_porep::stacked::vanilla::graph > using parents cache of unlimited size
2020-06-24T00:27:38.270 INFO storage_proofs_porep::stacked::vanilla::graph > using parent_cache[1073741824]
2020-06-24T00:27:46.655 INFO storage_proofs_porep::stacked::vanilla::proof > generate labels
memory allocation of 68719476736 bytes failedSIGABRT: abort
PC=0x7f7c8780fe97 m=11 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f7c8780fe97
stack: frame={sp:0x7f7c3d9edb50, fp:0x0} stack=[0x7f7c3d1eef08,0x7f7c3d9eeb08)
00007f7c3d9eda50:  0000000000000000  0002000000000000 
00007f7c3d9eda60:  00007f7c3d9edac0  00007f7c3d9edcf8 
00007f7c3d9eda70:  000000000118c600  000000000000002d 
00007f7c3d9eda80:  00007f7c3d9edbc8  00007f7c3d9edc78 
00007f7c3d9eda90:  00007f7c44000bf0  000000000190dd42 
00007f7c3d9edaa0:  000000000000002d  00007f7c38000dc0 
00007f7c3d9edab0:  00007f7c3d9edb10  00007f7c3d9edd48 
00007f7c3d9edac0:  000000000118c600  000000000000002d 
00007f7c3d9edad0:  00007f7c3d9edc18  00007f7c3d9edcc8 
00007f7c3d9edae0:  00007f7c44000bf0  000000000119508a 
00007f7c3d9edaf0:  000000000000002d  00007f7c87deb2cc 
00007f7c3d9edb00:  0000000190dd4203  000000000000000b 
00007f7c3d9edb10:  00007f7c3d9edcd8  7fffffffffffffff 
00007f7c3d9edb20:  000000000000000b  00007f7c87deb2cc 
00007f7c3d9edb30:  00007f7c3d9edb58  000000000000000d 
00007f7c3d9edb40:  00007f7c3d9edcd8  7fffffffffffffff 
00007f7c3d9edb50: <0000000000000000  000000000190fd4e 
00007f7c3d9edb60:  0000000000000003  00007f7c3d9edc08 
00007f7c3d9edb70:  0000000000000000  000000000000000b 
00007f7c3d9edb80:  00007f7c3d9edd48  00007f7c3d9edcd8 
00007f7c3d9edb90:  00007f7c3d9edd68  0000000003f8b4e0 
00007f7c3d9edba0:  0000000000000000  000000000000000d 
00007f7c3d9edbb0:  0000000000000001  00007f7c3d9edcd8 
00007f7c3d9edbc0:  00007f7c3d9edd68  0000000003f8b4e0 
00007f7c3d9edbd0:  fffffffe7fffffff  ffffffffffffffff 
00007f7c3d9edbe0:  ffffffffffffffff  ffffffffffffffff 
00007f7c3d9edbf0:  ffffffffffffffff  ffffffffffffffff 
00007f7c3d9edc00:  ffffffffffffffff  ffffffffffffffff 
00007f7c3d9edc10:  ffffffffffffffff  ffffffffffffffff 
00007f7c3d9edc20:  ffffffffffffffff  ffffffffffffffff 
00007f7c3d9edc30:  ffffffffffffffff  ffffffffffffffff 
00007f7c3d9edc40:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f7c8780fe97
stack: frame={sp:0x7f7c3d9edb50, fp:0x0} stack=[0x7f7c3d1eef08,0x7f7c3d9eeb08)
00007f7c3d9eda50:  0000000000000000  0002000000000000 
00007f7c3d9eda60:  00007f7c3d9edac0  00007f7c3d9edcf8 
00007f7c3d9eda70:  000000000118c600  000000000000002d 
00007f7c3d9eda80:  00007f7c3d9edbc8  00007f7c3d9edc78 
00007f7c3d9eda90:  00007f7c44000bf0  000000000190dd42 
00007f7c3d9edaa0:  000000000000002d  00007f7c38000dc0 
00007f7c3d9edab0:  00007f7c3d9edb10  00007f7c3d9edd48 
00007f7c3d9edac0:  000000000118c600  000000000000002d 
00007f7c3d9edad0:  00007f7c3d9edc18  00007f7c3d9edcc8 
00007f7c3d9edae0:  00007f7c44000bf0  000000000119508a 
00007f7c3d9edaf0:  000000000000002d  00007f7c87deb2cc 
00007f7c3d9edb00:  0000000190dd4203  000000000000000b 
00007f7c3d9edb10:  00007f7c3d9edcd8  7fffffffffffffff 
00007f7c3d9edb20:  000000000000000b  00007f7c87deb2cc 
00007f7c3d9edb30:  00007f7c3d9edb58  000000000000000d 
00007f7c3d9edb40:  00007f7c3d9edcd8  7fffffffffffffff 
00007f7c3d9edb50: <0000000000000000  000000000190fd4e 
00007f7c3d9edb60:  0000000000000003  00007f7c3d9edc08 
00007f7c3d9edb70:  0000000000000000  000000000000000b 
00007f7c3d9edb80:  00007f7c3d9edd48  00007f7c3d9edcd8 
00007f7c3d9edb90:  00007f7c3d9edd68  0000000003f8b4e0 
00007f7c3d9edba0:  0000000000000000  000000000000000d 
00007f7c3d9edbb0:  0000000000000001  00007f7c3d9edcd8 
00007f7c3d9edbc0:  00007f7c3d9edd68  0000000003f8b4e0 
00007f7c3d9edbd0:  fffffffe7fffffff  ffffffffffffffff 
00007f7c3d9edbe0:  ffffffffffffffff  ffffffffffffffff 
00007f7c3d9edbf0:  ffffffffffffffff  ffffffffffffffff 
00007f7c3d9edc00:  ffffffffffffffff  ffffffffffffffff 
00007f7c3d9edc10:  ffffffffffffffff  ffffffffffffffff 
00007f7c3d9edc20:  ffffffffffffffff  ffffffffffffffff 
00007f7c3d9edc30:  ffffffffffffffff  ffffffffffffffff 
00007f7c3d9edc40:  ffffffffffffffff  ffffffffffffffff 

goroutine 8272 [syscall]:
runtime.cgocall(0xec9910, 0xc001285300, 0xc00000e760)
        /usr/lib/go-1.14/src/runtime/cgocall.go:133 +0x5b fp=0xc0012852a8 sp=0xc001285270 pc=0x53159b
github.com/filecoin-project/filecoin-ffi/generated._Cfunc_fil_unseal_range(0xbda0512b00000003, 0xc00003b380, 0xa00000008, 0x1, 0x7e8, 0x0, 0x0, 0x0, 0xb243e526c051570e, 0xa1da9960b02eabe8, ...)
        _cgo_gotypes.go:1631 +0x51 fp=0xc001285300 sp=0xc0012852a8 pc=0xb10681
github.com/filecoin-project/filecoin-ffi/generated.FilUnsealRange(0xc000000003, 0xc00003b230, 0x2b, 0xa00000008, 0x1, 0x7e8, 0x0, 0x0, 0x0, 0x0, ...)
        /home/a/lotus/extern/filecoin-ffi/generated/generated.go:628 +0x2c7 fp=0xc001285478 sp=0xc001285300 pc=0xb1eda7
github.com/filecoin-project/filecoin-ffi.UnsealRange(0x3, 0xc00003b230, 0x2b, 0xc0000100b8, 0xc0000100c8, 0x1, 0x3e8, 0xc0000362e0, 0x20, 0x20, ...)
        /home/a/lotus/extern/filecoin-ffi/proofs.go:443 +0x3b6 fp=0xc0012856c8 sp=0xc001285478 pc=0xb28c26
github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).UnsealPiece(0xc0003ce4e0, 0x217a6e0, 0xc0000380e0, 0x3e8, 0x1, 0x0, 0x7f0000000, 0xc0000362e0, 0x20, 0x20, ...)
        /home/a/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200618073200-d9de9b7cb4b4/ffiwrapper/sealer_cgo.go:321 +0xa0e fp=0xc001285aa0 sp=0xc0012856c8 pc=0xb32ede
main.runSeals.func1.1(0x0, 0x1, 0x3e8, 0x4068110, 0x0, 0x0, 0xc0003d4100, 0xc0003ce4e0, 0xc0000a8a80, 0xc0003d4120, ...)
        /home/a/lotus/cmd/lotus-bench/main.go:626 +0xe3c fp=0xc001285e58 sp=0xc001285aa0 pc=0xec77ac
main.runSeals.func1(0x1, 0x3e8, 0x4068110, 0x0, 0x0, 0xc0003d4100, 0xc0003ce4e0, 0xc0000a8a80, 0xc0003d4120, 0x1, ...)
        /home/a/lotus/cmd/lotus-bench/main.go:641 +0x161 fp=0xc001285f30 sp=0xc001285e58 pc=0xec80c1
runtime.goexit()
        /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc001285f38 sp=0xc001285f30 pc=0x593211
created by main.runSeals
        /home/a/lotus/cmd/lotus-bench/main.go:502 +0x709

goroutine 1 [chan receive, 293 minutes]:
main.runSeals(0xc0003ce4e0, 0xc0003d4020, 0x1, 0x1, 0x1, 0x1, 0x3e8, 0x800000000, 0x4068110, 0x0, ...)
        /home/a/lotus/cmd/lotus-bench/main.go:651 +0x780
main.glob..func3(0xc0003c6800, 0x0, 0x0)
        /home/a/lotus/cmd/lotus-bench/main.go:247 +0x6f4
github.com/urfave/cli/v2.(*Command).Run(0x3fd0680, 0xc0003c6440, 0x0, 0x0)
        /home/a/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc0003cca80, 0x217a6e0, 0xc0000380c8, 0xc0000321e0, 0x6, 0x6, 0x0, 0x0)
        /home/a/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
        /home/a/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        /home/a/lotus/cmd/lotus-bench/main.go:90 +0x286

goroutine 6 [select, 302 minutes]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0000b3a10)
        /home/a/go/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:71 +0x128
created by github.com/ipfs/go-log/writer.NewMirrorWriter
        /home/a/go/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:36 +0xb9

goroutine 7 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000a6a00)
        /home/a/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
        /home/a/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x57

goroutine 7382 [IO wait]:
internal/poll.runtime_pollWait(0x7f7c8866cea8, 0x72, 0xffffffffffffffff)
        /usr/lib/go-1.14/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000152e58, 0x72, 0x1fc00001, 0x1fc00000, 0xffffffffffffffff)
        /usr/lib/go-1.14/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/go-1.14/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000152e40, 0xc004b00000, 0x1fc00000, 0x1fc00000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.14/src/internal/poll/fd_unix.go:169 +0x19b
os.(*File).read(...)
        /usr/lib/go-1.14/src/os/file_unix.go:263
os.(*File).Read(0xc0000100c0, 0xc004b00000, 0x1fc00000, 0x1fc00000, 0x1d76540, 0x1d86c01, 0x0)
        /usr/lib/go-1.14/src/os/file.go:116 +0x71
io.(*LimitedReader).Read(0xc000182020, 0xc004b00000, 0x1fc00000, 0x1fc00000, 0x0, 0x53ad00, 0xc000182020)
        /usr/lib/go-1.14/src/io/io.go:451 +0x63
bufio.(*Writer).ReadFrom(0xc00041c0c0, 0x21612e0, 0xc000182020, 0x7f7c5c247008, 0xc00041c0c0, 0x56bc01)
        /usr/lib/go-1.14/src/bufio/bufio.go:728 +0xf1
io.copyBuffer(0x215f9c0, 0xc00041c0c0, 0x21612e0, 0xc000182020, 0x0, 0x0, 0x0, 0x1e0a400, 0x213d368, 0x0)
        /usr/lib/go-1.14/src/io/io.go:391 +0x2fc
io.Copy(...)
        /usr/lib/go-1.14/src/io/io.go:364
io.CopyN(0x215f9c0, 0xc00041c0c0, 0x2161780, 0xc0000100c0, 0x7f0000000, 0x0, 0x1d6aae0, 0x1)
        /usr/lib/go-1.14/src/io/io.go:340 +0x9a
github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).UnsealPiece.func1(0xc0000a8840, 0xc0000100c0, 0x21617c0, 0xc0000100b0, 0xc000414150, 0xc000414160, 0x7f0000000)
        /home/a/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200618073200-d9de9b7cb4b4/ffiwrapper/sealer_cgo.go:301 +0x2a1
created by github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).UnsealPiece
        /home/a/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200618073200-d9de9b7cb4b4/ffiwrapper/sealer_cgo.go:284 +0x93b

rax    0x0
rbx    0x1000000000
rcx    0x7f7c8780fe97
rdx    0x0
rdi    0x2
rsi    0x7f7c3d9edb50
rbp    0xb
rsp    0x7f7c3d9edb50
r8     0x0
r9     0x7f7c3d9edb50
r10    0x8
r11    0x246
r12    0x7f7c3d9ee020
r13    0x40000000
r14    0x0
r15    0x7f7c3d9ee4f0
rip    0x7f7c8780fe97
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version (run `lotus --version`):**

**Additional context**
Add any other context about the problem here.
