### ISSUE TITLE
Need an entry to send the raw transaction

### ISSUE THREAD

**Issue by yancaitech** [filecoin-project/lotus#2006]
Need an entry to send the raw transaction

Transactions generated by other wallets or websites need to be passed to the node.

May need to add subcommand "sendrawtransaction" in mpool command.

It is better to use hex string format.
*types.SignedMessage -> Serialize()  -> hex.EncodeToString

**Comment by magik6k** [comment]
MpoolPush is the API you want -> https://github.com/filecoin-project/lotus/blob/master/api/api_full.go#L78

It currently only supports json-encoded messages (There was a PR which made it possible to pass it as a base64 string - https://github.com/filecoin-project/lotus/pull/1108, but it never got merged, and now would need to get ported to go-jsonrpc repo)

Thinking about this now it's probably best to imploment a custom unmarshaler on the messsage type which would handle that, instead of doing this on go-jsonrpc level

**Comment by yancaitech** [comment]
> 
> 
> MpoolPush is the API you want -> https://github.com/filecoin-project/lotus/blob/master/api/api_full.go#L78
> 
> It currently only supports json-encoded messages (There was a PR which made it possible to pass it as a base64 string - #1108, but it never got merged, and now would need to get ported to go-jsonrpc repo)
> 
> Thinking about this now it's probably best to imploment a custom unmarshaler on the messsage type which would handle that, instead of doing this on go-jsonrpc level

OK, I hope it can be done when the mainnet goes online, which will facilitate the development of third-party wallets.
