### ISSUE TITLE
the  runSched() of miner  was  blocked and can't schedule any tasks

### ISSUE THREAD

**Issue by gavin-ygy** [filecoin-project/lotus#2080]
**Describe the bug**
When the bug happens,  all the P1/P2/C1/C2 tasks in the cluster will stay at  the same state  for long time and can't enter into new state. And the new worker can't be checked by cmd "lotus-storage-miner workers list". 

**To Reproduce**
1. run lotus-storage-miner in a AMD machine
2. run five  lotus-seal-worker in different AMD machines
3.  keep every worker to compute the task
4.  Unplug the network cable of some worker machine. After a while , plug the cable of the worker and restart the lotus-seal-worker in the machine.
5.  Every about five minutes, repeat the step 4 until the cmd "lotus-storage-miner workers list" can't find the new worker of during step 4 restarting. 

**Expected behavior**

**Screenshots**

**Version (run `lotus --version`):**
lotus version 0.4.0+git.ffa7be86

**Additional context**
the bug was caused by the two channel blocking .
1.  sh.watchClosing in runSched()
2.  sh.workerClosing in  runWorkerWatcher()

func (sh *scheduler) runSched() {
	go sh.runWorkerWatcher()

	for {
		select {
		case w := <-sh.newWorkers:
			sh.schedNewWorker(w)  ===> the function was blocked at channel: sh.watchClosing
		case wid := <-sh.workerClosing:
			sh.schedDropWorker(wid)
		case req := <-sh.schedule:
			scheduled, err := sh.maybeSchedRequest(req)
			if err != nil {
				req.respond(err)
				continue
			}

			if scheduled {
				continue
			}

			heap.Push(sh.schedQueue, req)
		case wid := <-sh.workerFree:

			sh.onWorkerFreed(wid)
		
		case <-sh.closing:
			sh.schedClose()
			return
		}
	}
}
==============
func (sh *scheduler) runWorkerWatcher() {
	ctx, cancel := context.WithCancel(context.TODO())
	defer cancel()

	nilch := reflect.ValueOf(new(chan struct{})).Elem()

	cases := []reflect.SelectCase{
		{
			Dir:  reflect.SelectRecv,
			Chan: reflect.ValueOf(sh.closing),
		},
		{
			Dir:  reflect.SelectRecv,
			Chan: reflect.ValueOf(sh.watchClosing),
		},
	}

	caseToWorker := map[int]WorkerID{}

	for {
		n, rv, ok := reflect.Select(cases)
		switch {
		case n == 0: // sh.closing
			return
		case n == 1: // sh.watchClosing
	
			if !ok {
				log.Errorf("watchClosing channel closed")
				return
			}

			wid, ok := rv.Interface().(WorkerID)
			if !ok {
				panic("got a non-WorkerID message")
			}

			sh.workersLk.Lock()
			workerClosing, err := sh.workers[wid].w.Closing(ctx)
			sh.workersLk.Unlock()
			if err != nil {
				log.Errorf("getting worker closing channel: %+v", err)
				select {
				case sh.workerClosing <- wid:
	
				case <-sh.closing:
					return
				}

				continue
			}

			toSet := -1
			for i, sc := range cases {
				if sc.Chan == nilch {
					toSet = i
					break
				}
			}
			if toSet == -1 {
				toSet = len(cases)
				cases = append(cases, reflect.SelectCase{})
			}

			cases[toSet] = reflect.SelectCase{
				Dir:  reflect.SelectRecv,
				Chan: reflect.ValueOf(workerClosing),
			}

			caseToWorker[toSet] = wid
		default:
			wid := caseToWorker[n]

			delete(caseToWorker, n)
			cases[n] = reflect.SelectCase{
				Dir:  reflect.SelectRecv,
				Chan: nilch,
			}

			log.Warnf("worker %d dropped", wid)
			select {
			case sh.workerClosing <- wid:  ===> the channel was blocked!!
				log.Infof("---ygy--- Sched_watch  888, send ch ok:workerClosing! wid=",wid)
			case <-sh.closing:
				log.Infof("---ygy--- Sched_watch 9999,  channel sh.closing !!!")
				return
			}
		}
	}

**Comment by hayeah** [comment]
Here's my analysis of what's going on... 

1. `sh.workerClosing <- wid` this is blocked because `workersLk` is locked
  * causes runWorkerWatcher to block up
2. sh.schedNewWorker is blocked because `sh.watchClosing` is blocked
  * because runWorkerWatcher loop is no longer running to consume watchClosing

This is just the symptom, the question is why `workersLk` is locked. Reviewing all places where `workersLk.Lock()` is called, the most suspect is `maybeSchedRequest`, when it loops over all workers (including remote workers) to call `selector.Ok`:

```
for wid, worker := range sh.workers {
		ok, err := req.sel.Ok(req.ctx, req.taskType, sh.spt, worker)
		if err != nil {
			return false, err
		}

		if !ok {
			continue
		}
		tried++

		if !canHandleRequest(needRes, sh.spt, wid, worker.info.Resources, worker.preparing) {
			continue
		}

		acceptable = append(acceptable, wid)
	}
```

`task_selector.go`, for example, would call `worker.TaskTypes` via RPC. If any of the RPC hangs (in this case, unplugged cable), `maybeSchedRequest` would keep the lock. 

The whole scheduler locks up.

## WebSocket Conn

Why does the RPC hangs? On abnormal closure, the underlying websocket conn would attempt to [reconnect](https://github.com/filecoin-project/go-jsonrpc/blob/master/websocket.go#L482-L510) for abnormal closure.

But because the node is down, it just keeps retrying.

Where if a node had gone down "properly", `CloseNormalClosure` would not attempt to reconnect.

## Fix

* Temporary: just comment out the whole websocket reconnect thing.

Proposal: Add a timeout in [`maybeSchedRequest` when calling `req.sel.Ok`](https://github.com/filecoin-project/sector-storage/blob/ffbfa84591326544bce4b3fd14a7e0e3d3182dc2/sched.go#L217) (like 5s or something...). If a worker timesout, skip it.
