### ISSUE TITLE
API for sector lifecycle upgrade

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/lotus#2100]
Placeholder issue for planned API additions to support making & checking sector lifecycle upgrades.

@popra and team are planning to use this API in an application they're currently building. @magik6k @arajasek can they get an example of the planned API call & response(s) in advance? Especially interested in the response that shows at least one commit sector upgrade was done on a sector.

For miners with large numbers of sectors (based on the results of StateMinerSectorCount, e.g. 1000+) any recommendations on how to efficiently handle these cases? We are looking to check only that it was done on *any* sector for that miner. cc @ianjdarrow

**Comment by magik6k** [comment]
Making CC upgrades will be done with one of the following:
1. API call to force upgrade a given SectorNum when we have a sector with deals
2. Always try to upgrade CC sectors 
3. Only update when out of space for accepting deals

For testnet incentives we'll implement either 1, or 2 (with some on/off switch), but 3. is really the only case in which this mechanism is useful for miners

There will be no new APIs which would allow observing that a miner has performed a  CC upgrade, because it's not something you can easily get from the chain state - you should be able to observe that by:
* Looking at miner precommit messages, and seeing if they are setting the `ReplaceSector` field - https://github.com/filecoin-project/specs-actors/pull/514/files#diff-2580e4b82238370ee854a52e8d5428e7R129
* Making sure that those messages are successful (by checking receipts)
* At some later point making sure that the replaced sector was successfully committed (either by checking the miner actor state or by looking for corresponding CommitSector message)

(you could use / extend the chainwatch database schema to handle this https://github.com/filecoin-project/lotus/blob/master/cmd/lotus-chainwatch/storage.go#L194-L251)

**Comment by popra** [comment]
cc @stefangeorgerobert

**Comment by stefangeorgerobert** [comment]
@magik6k Can this be simplified by adding **Upgraded** field to the response of StateMinerSectors api ? Pls see the example bellow.

**Filecoin.StateMinerSectors(miner)**

_{"jsonrpc":"2.0","result":
[{"Info":{"Info":{"RegisteredProof":1,"SectorNumber":0,**"Upgraded":1**,"SealedCID":{"/":"bafk4ehzadb3chwdbemopvkzmsltaq3765suauzleh4fkb5mqzysq2d7dryxa"},"SealRandEpoch":84962,"DealIDs":null,"Expiration":10089734},"ActivationEpoch":87047,"DealWeight":"0","VerifiedDealWeight":"0"},"ID":0},
 {"Info":{"Info":{"RegisteredProof":1,"SectorNumber":1,**"Upgraded":0**,"SealedCID":{"/":"bafk4ehzadjtsrng5syrp7gcm4ivqvcopmfjibnbwjdwieulvf5kxmz3ityuq"},"SealRandEpoch":84988,"DealIDs":null,"Expiration":10089734},"ActivationEpoch":87240,"DealWeight":"0","VerifiedDealWeight":"0"},"ID":1},
 {"Info":{"Info":{"RegisteredProof":1,"SectorNumber":2,**"Upgraded":0**,"SealedCID":{"/":"bafk4ehzag5aoerknloctxh24wtgx7okw25ifkki2nmbqdbu3u2sopyxq4zaa"},"SealRandEpoch":85013,"DealIDs":null,"Expiration":10089734},"ActivationEpoch":87814,"DealWeight":"0","VerifiedDealWeight":"0"},"ID":2},
 {"Info":{"Info":{"RegisteredProof":1,"SectorNumber":3,**"Upgraded":0**,"SealedCID":{"/":"bafk4ehzakrcpo7gpt5cmp2dkew4hclwf3ppdhexycng2fulsjordk3uyanrq"},"SealRandEpoch":85037,"DealIDs":null,"Expiration":10089734},"ActivationEpoch":86751,"DealWeight":"0","VerifiedDealWeight":"0"},"ID":3},
 {"Info":{"Info":{"RegisteredProof":1,"SectorNumber":5,**"Upgraded":0**,"SealedCID":{"/":"bafk4ehzazbht5ae62vlrvbuydsyippqtvqhiuhbu7c4m43yomjuerjanheaq"},"SealRandEpoch":85942,"DealIDs":null,"Expiration":10089734},"ActivationEpoch":88038,"DealWeight":"0","VerifiedDealWeight":"0"},"ID":5},
],"id":3}_

**Comment by arajasek** [comment]
@stefangeorgerobert I don't think that'll be possible, since this isn't information you can find by looking at the state at any particular height. You necessarily need to be examining some section of the chain, which isn't what the `State` methods do.

**Comment by stefangeorgerobert** [comment]
@mishmosh, @arajasek , @magik6k 

Can you please provide more details for each step, how can we implement this using the lotus APIs (rpc) ? We need to implement this in an external tool (Bot) and we interact with the lotus node via lotus APIs. 

1. - Looking at miner precommit messages, and seeing if they are setting the ReplaceSector field - https://github.com/filecoin-project/specs-actors/pull/514/files#diff-2580e4b82238370ee854a52e8d5428e7R129
2. - Making sure that those messages are successful (by checking receipts)
3. - At some later point making sure that the replaced sector was successfully committed (either by checking the miner actor state or by looking for corresponding CommitSector message)

**Comment by jennijuju** [comment]
implemented in https://github.com/filecoin-project/lotus/blob/a152d98af82b3e8bfae0c9b7766eda1ac78db76b/api/api_storage.go#L60
