### ISSUE TITLE
Client Retrieve Command Should Specify Parameters For Deal

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#2151]
# Why

Currently, the retrieval command queries all the miners it knows who may have a payloadCID and simply retrieves from the first one it hears back from (offers[0] in the list of query offers.

This presents a number of issues -- most specifically, that the price for the retrieval could be anything!

# What

As a starting point, we should probably sort offers by price.

However, we should also specify a maximum price on the command line -- possibly as a mandatory parameter (possibly optional but with a default limit and a message if it goes over)

We could also optionally allow specifying other parameters as needed.

**Comment by mgoelzer** [comment]
Thumbs up on this!

I'd vote to get rid of that whole block where we do [`offer = offers[0]`](https://github.com/filecoin-project/lotus/blob/fe4efa0e0ee045d38f63f4955d01cbf3e36bc41f/cli/client.go#L453) and instead have `ClientRetrieve` require a miner id (no if-else to catch the case where miner id is not provided).  The client will know the miner ids since it presumably called `ClientFindData` immediately before it calls `ClientRetrieve`.

+1 on maximum price so that miners don't quickly jack up their price after being hit with a `ClientQueryAsk`.
