### ISSUE TITLE
lotus-storage-miner crashes on restart with segfault

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#2164]
**Describe the bug**

Miner crashes with a segfault on restart (testnet).

Logs attached.

[miner-crash.log](https://github.com/filecoin-project/lotus/files/4842725/miner-crash.log)

**Version (run `lotus --version`):**

```
$ ./lotus --version
lotus version 0.4.0+git.fbfe57cd
```

**Comment by jimpick** [comment]
I did a `git pull` and `make` just prior to restarting.

**Comment by viking2015** [comment]
@jimpick Are you fix this ?

**Comment by RobQuistNL** [comment]
Same issue here. Before pledging the first sector I also had similar segfaults on running `lotus-storage-miner info`

```
filecoin@filecoin-desktop:~$ lotus-storage-miner info
Miner: t0118070
Sector Size: 32 GiB
Byte Power:   0 B / 11.4 PiB (0.0000%)
Actual Power: 0  / 11.1 Pi (0.0000%)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1568c97]

goroutine 1 [running]:
main.glob..func2(0xc0006dfac0, 0x0, 0x0)
	/home/filecoin/lotus/cmd/lotus-storage-miner/info.go:104 +0xc37
github.com/urfave/cli/v2.(*Command).Run(0x4d422a0, 0xc0006df9c0, 0x0, 0x0)
	/home/filecoin/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc000102900, 0x2b9de60, 0xc00003e0a0, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
	/home/filecoin/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/home/filecoin/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/home/filecoin/lotus/cmd/lotus-storage-miner/main.go:83 +0x6e6
```

**Comment by jimpick** [comment]
Thanks! My miner is alive again!

**Comment by yu-val-cho** [comment]
@ jimpick 
how did u solve it?  we r in china, with lots of issues. but right now stuck at the same place with the same error. did update to latest lotus?

**Comment by jimpick** [comment]
@yu-val-cho I updated to the latest lotus and that fixed the problem.

Possibly you are getting a segmentation fault because of a different problem. If you are still experiencing segmentation faults, you should file them as a new issue and attach a log file and the team will take a look at it, as it is possibly a new bug.

**Comment by yu-val-cho** [comment]
Thanks for the quick response.
Updating to the latest version fixed it. Our main issue with running the
processes is that each time we need to rerun everything, and while we found
out how to keep the 2 huge files for proofs (which are difficult to
download in china) we are not sure how to not lose all of our chain data.
We have to resync it from zero each time.
We couldn't find anywhere how to do that.
Do you know how or if we can use our old folders/files in order to not sync
from zero? that will be a huge time saver for us and we can test the
testnet better and more efficiently.

Thanks,
Yuval
