### ISSUE TITLE
Only sync one 'long' chain at a time

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#2200]
The chain sync manager will run multiple sync tasks in parallel, to ensure that we process incoming blocks in a timely manner. This is intended to only sync short lengths of chain that are 'fresh' in the network. However, in some cases, if we have a longish chain to sync, and are not in the 'bootstrap' mode, we will end up syncing long chains on all sync workers. This is usually syncing the same chain on each, just with a different height, or something.

We should ensure this doesnt happen, if we are in the process of syncing a long chain, don't start any new sync tasks. (this mechanism can also be used to replace the 'bootstrap' sync mode thing)

**Comment by frrist** [comment]
From my reading of the sync manager, I believe this is more or less addressed -- specifically as a part of #4599, which was merged long after this issue was created. But for completeness...

When the sync manager is selecting a target to sync, it will first check if if the target is related to any active sync, aborting the sync if that is the case, or scheduling it for later:
https://github.com/filecoin-project/lotus/blob/a584fcb935c084f26bb88def6b5a21ec9b6c623b/chain/sync_manager.go#L378-L387

Next, it checks if the target is related to any pending sync, again aborting if true:
https://github.com/filecoin-project/lotus/blob/a584fcb935c084f26bb88def6b5a21ec9b6c623b/chain/sync_manager.go#L392-L395

Lastly, the syncManager will check if it is still in the `initial sync phase (or the 'bootstrap' phase as Why describes it) before it accepts the target and starts a new worker:
https://github.com/filecoin-project/lotus/blob/a584fcb935c084f26bb88def6b5a21ec9b6c623b/chain/sync_manager.go#L413-L417

The method comment at the end is most telling here:
https://github.com/filecoin-project/lotus/blob/a584fcb935c084f26bb88def6b5a21ec9b6c623b/chain/sync_manager.go#L419

I am going to close this due to my reasoning above.
