### ISSUE TITLE
lotus-bench's HowTo document is not updated in documentation/en/

### ISSUE THREAD

**Issue by UltraVis** [filecoin-project/lotus#2224]
**Describe the bug**
"documentation/en/" does not contain an updated information/HowTo on 'lotus-bench', which appears to be just 'bench' now, which new options available?

**To Reproduce**

1. Look for lotus-bench's howto's and follow the any instruction given

**Expected behavior**
Being able to find concise info on lotus-bench to facilitate system benchmarking and testing

**Screenshots**
N/A

**Version (run `lotus --version`):**
lotus version 0.4.0+git.70d83784.dirty

**Comment by hsanjuan** [comment]
Added this to tutorials list (internal doc) for docs.filecoin.io

**Comment by Reiers** [comment]
**Hi @UltraVis** 

Thanks for the report. Issue is outdated and is fixed in our latest release. 

```
./lotus-bench --help
2022-01-18T21:41:05.931+0100	INFO	lotus-bench	lotus-bench/main.go:103	Starting lotus-bench
NAME:
   lotus-bench - Benchmark performance of lotus on your hardware

USAGE:
   lotus-bench [global options] command [command options] [arguments...]

VERSION:
   1.14.0-rc1+mainnet

COMMANDS:
   prove    Benchmark a proof computation
   sealing  Benchmark seal and winning post and window post
   import   Benchmark chain import and validation
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help (default: false)
   --version, -v  print the version (default: false)
```

More about lotus-bench, [here. ](https://lotus.filecoin.io/docs/storage-providers/benchmarks/)

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)
