### ISSUE TITLE
Under what conditions can a miner safely reboot their miner?

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#2803]
There are critical windows when a miner will need to perform maintenance on their host that is running the lotus miner. How does a miner determine when they can safely shutdown their miner for up to 30 minutes without being penalized?

**Comment by junyaoren** [comment]
This is a problem we care a lot. We have had a lot of pain to recover a miner after it is shut down by system (due to OOM issue) or restarts from a panic. Some files seem to broke because of these "ungraceful shutdown" and it is very difficult to recover, which would be huge trouble once a miner has gained a large amount of power.

**Comment by ytQiao** [comment]
Yes, I think these problems must be solved before the space race. The code of the space race should be basically consistent with the online code of the main network. Obviously, it can't be done at present @travisperson

**Comment by rjan90** [comment]
I think this issue can be closed, as the docs explains how to `Safely Reboot the Miner`: https://docs.filecoin.io/mine/lotus/miner-lifecycle/#safely-restarting-the-miner-daemon. #rengjøring
