### ISSUE TITLE
Node won't start after disk full ... leveldb corrupted

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#3231]
**Describe the bug**

I ran out of disk space on my node. After adding more disk and restarting, my node complains and won't start:

```
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/home/ubuntu/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.MetadataDS: function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12) returned a non-nil error: opening datastore /metadata: leveldb/journal: block/chunk corrupted: chunk length overflows block (2124 bytes) [file=000043.log]
```

**To Reproduce**
1. Fill up disk space
2. Restart node

**Expected behavior**

Node should start after disk space is available.

**Version (run `lotus version`):**

```
commit 5c6b99c9dc7dbbce567813db40faf3df827db4de (HEAD -> ntwk-calibration, tag: ntwk-calibration-8.19.1, origin/ntwk-calibration)
Merge: a60c6e0b 885f357c
Author: _ukasz Magiera <magik6k@users.noreply.github.com>
Date:   Thu Aug 20 02:30:35 2020 +0200

    Merge pull request #3177 from filecoin-project/master
    
    Merge latest master into ntwk-calibration
```

**Comment by Wondertan** [comment]
Run into this as well and removing `.log` file just makes everything worse. Now I lost all the sector refs in datastore ;(

**Comment by Reiers** [comment]
Hi @jimpick 

Thanks for the report. The issue is outdated - keep track of chain size and prune if needed.
https://lotus.filecoin.io/docs/set-up/chain-management/

Its easier to get out of this state - on the [latest release. ](https://github.com/filecoin-project/lotus/releases/tag/v1.14.4)

Ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions) or open a new issue if this is something you think we should take another look at. 

Thank you !
