### ISSUE TITLE
Lotus VM throws incorrect error on unparsable params

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#3264]
These two test vectors are broken:

1. [`actor_creation/x--params--fails-unparsable-init-actor-exec-msg.json`](https://github.com/filecoin-project/test-vectors/blob/master/corpus/actor_creation/x--params--fails-unparsable-init-actor-exec-msg.json) [(generation script)](https://github.com/filecoin-project/test-vectors/blob/e3b6da3c2e3b228515d69250999babbcd09198b4/gen/suites/actor_creation/params.go#L15): tests the exit code when we send corrupt parameters to `InitExec`.
2. [`actor_creation/x--params--fails-unparsable-constructor-params-via-init-actor.json`](https://github.com/filecoin-project/test-vectors/blob/master/corpus/actor_creation/x--params--fails-unparsable-constructor-params-via-init-actor.json) [(generation script)](https://github.com/filecoin-project/test-vectors/blob/e3b6da3c2e3b228515d69250999babbcd09198b4/gen/suites/actor_creation/params.go#L41): tests the exit code when we send a correct `InitExec` message, but the inner constructor parameters are corrupt.

They both return `SysErrSenderInvalid`, but the exit code should be different. @anorth to confirm which one, possibly `SysErrSerialization` for (1), and `ErrSerialization` for (2). Open question here: https://github.com/filecoin-project/test-vectors/pull/41#discussion_r475604234

Also noteworthy is that despite returning `SysErrSenderInvalid`, gas is being deducted, which I'm told should not be the case, and therefore it may indicate a deeper problem.

---

These vectors are currently marked as `incorrect`, and as soon as we deliver https://github.com/filecoin-project/test-vectors/issues/72, they should be excluded from the standard `test-conformance` test suite run, and tested only in a `test-conformance-incorrect` suite.

**Comment by Kubuxu** [comment]
We don't use `SysErrSenderInvalid` as sentinel error for not deducting gas so afaik there is no deeper error there.

**Comment by anorth** [comment]
`SysErrSerialization` has been removed from the actors code (Lotus doesn't reference it). `ErrSerialization` is the right code.

> We don't use SysErrSenderInvalid as sentinel error for not deducting gas

I guess mechanism choice is up to you, but there should be *no possibility* of producing a `SysErrSenderInvalid` or `SysErrSenderStateInvalid` and still charging gas to the sender. Those two exit codes exist specifically to identify cases where the sender cannot be charged gas. This suggests that the current use of those exit codes is incorrect.

```
	// Indicates that the actor identified as the sender of a message is not valid as a message sender:
	// - not present in the state tree
	// - not an account actor (for top-level messages)
	// - code CID is not found or invalid
	// (not found in the state tree, not an account, has no code).
	SysErrSenderInvalid = ExitCode(1)

	// Indicates that the sender of a message is not in a state to send the message:
	// - invocation out of sequence (mismatched CallSeqNum)
	// - insufficient funds to cover execution
	SysErrSenderStateInvalid = ExitCode(2)
```

We also since strengthened block validation to make all the `SysErrSenderInvalid` cases impossible, before the VM is invoked. It makes some sense that code checking those conditions still exist in the VM, and it if didn't return `SysErrSenderInvalid` it would probably panic (precondition not met). But it does mean that if that exit code escapes the VM, something is very wrong.

From https://github.com/filecoin-project/specs/issues/934
> Note that requiring the nonces to match the declared parent state implicitly requires that the sending actor exists in the parent state (which is already also required by signature validation). Since actor-creation is monotonic we could include all of the conditions covered by SysErrSenderInvalid in this block semantic validation, leaving "insufficient funds" as the only miner-penalising case.

**Comment by Kubuxu** [comment]
I just added a reference to it in #3267 but will change to `ErrSerialization`.

The reason for producing that exit code was due to a bug in the invoker (it was just using the exit code 1). I will audit all uses of `aerrors.Absorb` and `aerrors.New`.

**Comment by Kubuxu** [comment]
Solved in https://github.com/filecoin-project/lotus/pull/4783
