### ISSUE TITLE
Request: Clean shutdown/stop command for lotus-worker

### ISSUE THREAD

**Issue by Meatball13** [filecoin-project/lotus#3439]
**Describe the bug**
Not really a bug, more of a request.  Right now the only way to stop a lotus-worker is to kill the process. 

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**
Could we please get some sort of 'lotus-worker stop' command that would gracefully shut down the worker and hopefully save the state of the task it's working on so it can pick back up without a problem on restart?

**Screenshots**

**Version (run `lotus version`):**
  0.5.6+git.606a58bc

**Additional context**

**Comment by rjan90** [comment]
Closing this issue since the `lotus-worker` has a stop command now. The stop command also fixes other `lotus-worker` lifecycle issues like the frequent logs-warnings when the worker was lost, as well as detaching the storage location of the worker properly.

We are still tracking, and working towards a fix to the issue where setting the lotus-worker to disabled prevents other workers to fetch finished jobs from their storage.

**Comment by donkabat** [comment]
I suggest to remove stopped workers from `lotus-miner sealing workers` after `lotus-worker stop`

**Comment by rjan90** [comment]
Want to write up an [enhancment request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) for that @donkabat. It makes things easier to track for the devs rather then subcomments on other feature request threads 😄! Else I will write something up during the week

**Comment by donkabat** [comment]
@rjan90 I found opened and almost the same issue: [https://github.com/filecoin-project/lotus/issues/9132](9132)
and I added my comment there
