### ISSUE TITLE
Provider faces stream reset issues

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#3469]
2020-09-01T17:03:06.933+0800    ERROR   storagemarket_impl       impl/provider.go:492    failed to write deal status response: stream reset

@hannahhoward 's response to this:

_"To clarify, what I mean is shouldn’t we attempt to open a new connection and retry send? Actually graphsync’s code already does this: https://github.com/ipfs/go-graphsync/blob/master/messagequeue/messagequeue.go#L163 — but I’m assuming this is particular error is on a market’s specific libp2p protocol"_

**Comment by ingar** [comment]
@hannahhoward what do you think would cause a stream reset in this case?  The code here is a request/response initiated from the client; it seems like the client should retry the query, instead of the provider retrying the send?

**Comment by ingar** [comment]
I guess I'm asking because intent is that the Client will re-issue the query if they get an error:

https://github.com/filecoin-project/go-fil-markets/blob/master/storagemarket/impl/clientstates/client_states.go#L168-L171

Is this error causing a deal failure?

**Comment by hannahhoward** [comment]
Follow-up: I no longer think the change I recommended above makes sense. If the provide is unable to send a response, and client gets an error on the stream, it will automatically retry the query. https://github.com/filecoin-project/go-fil-markets/blob/master/storagemarket/impl/clientstates/client_states.go#L167 — you can see this is happening by the fact that the message appears multiple times sequentially in miner logs where this occurs — the miner is receiving the query, and for whatever reason repeatedly getting stream resets on the response. I don’t know why this is happening, but since connection is already tagged with a high priority value, and the amount of processing between request and response is minimal for this deal status call, I don’t think adding connection reopening logic will help.
