### ISSUE TITLE
[Feature Request]API to kill specific scheduler tasks.

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3564]
An API + CLI to kill a a specific job for sched.

**Comment by V3GTAM** [comment]
Ideally I would like to be able to remove a queued task from the scheduler before it starts and I would like to have some ability to kill specific running jobs. 

For example I have a situation like this: 
```
miner@ip-XXX-XX-XXX-XXX:~$ lotus-miner sealing jobs
ID   Sector  Worker  Hostname          Task  State    Time
832  35      10      ip-XXX-XX-XXX-XX1   PC1   running  5h27m32.5s
144  34      9       ip-XXX-XX-XXX-XX1   PC1   running  5h27m21.9s
398  37      3       ip-XXX-XX-XXX-XX1   PC1   running  2h23m4.6s
146  36      4       ip-XXX-XX-XXX-XX1   PC1   running  2h15m50.8s
31   32      16      ip-XXX-XX-XXX-XX2   PC2   running  1h11m29s
470  0       5       ip-XXX-XX-XXX-XX1   PC1   running  1h8m52.4s
369  38      2       ip-XXX-XX-XXX-XX1   PC1   running  57m29.8s
```

I need to perform some maintenance on my PC1 machine (ending in 1). I am currently waiting until my PC1 tasks all complete before shutting any worker tasks because I am unsure which actual process on the remote worker machine is performing what job and I don't want to inadvertently cause problems. I would be willing to loose the work done on sector 0 and 38 but I would like to wait for my work on sectors 34 and 35 to complete because they are almost done. 

It would be nice if I had some command to individually kill a specific job by ID, maybe something like

`lotus-miner sealing stop-job <ID>`

that would gracefully exit the job and save whatever is possible for a graceful restart.

Also it would be nice if I could remove a worker from the scheduling pool so I can allow the current jobs to complete before gracefully shutting down without loosing any work, especially because often different sectors are at different stages of jobs at any given point and new ones are automatically started so its hard to find the best time to stop the processes. If I had something like:

`lotus-miner sealing stop-giving-work-to <WORKER-ID>` 

that would remove a worker or group of workers/workers on an IP address from being scheduled for further jobs, I would find that very helpful. 

I think that commands like this would make the maintenance and operation of remote workers machines much easier.

**Comment by jennijuju** [comment]
`lotus-miner sealing  abort` exists.
