### ISSUE TITLE
 failed to start deal: computing commP failed: 

### ISSUE THREAD

**Issue by XIAOYAOSHUJU** [filecoin-project/lotus#3574]

**Comment by XIAOYAOSHUJU** [comment]
ERROR: failed to start deal: computing commP failed: generating CommP: failed to build tree
lotus client deal bafykbzacedxhzuflis64exqrlrdabo3ja3svlavncrpleei33s3fnfvmzx2se t017656 0.0000000005 518400
Caused by:
    0: failed to create data store
    1: No such file or directory (os error 2)

**Comment by Reiers** [comment]
Hi @XIAOYAOSHUJU 

Not a lot to go on here - the issue is outdated, and there no repro steps for me to do.

Please read this:
https://lotus.filecoin.io/docs/developers/store-data/

and if you are still experiencing problems, open a new ticket with more information or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thanks!
