### ISSUE TITLE
TestCCUpgrade is flaky

### ISSUE THREAD

**Issue by vyzo** [filecoin-project/lotus#3621]
See https://app.circleci.com/pipelines/github/filecoin-project/lotus/8846/workflows/aa7988b5-a336-462d-af3a-7d5e0bda2c00/jobs/54713

**Comment by Stebalien** [comment]
It's now flaky for a different reason. Specifically, https://github.com/filecoin-project/go-fil-markets/issues/614.

Basically, payment channel creation fails because we _create_ the payment channel create message on one side of an upgrade, then execute the message on the other.

The fix is to either:

1. Fix the underlying issue (difficult and not likely to be worth it at the moment).
2. Instead of just hard-coding the upgrade heights then assuming the deal creation will happen at the right spot, _wait_ until the upgrade has happened (for the epoch 560 case, at least) _then_ make the deal.

**Comment by Stebalien** [comment]
Alternatively, stop abusing this test? I mean, we're testing CC upgrades, CC upgrades over network upgrades, _and_ retrieval deals.

**Comment by rjan90** [comment]
Closing this issue since it seems like TestCCUpgrade is not flaky anymore. We will open a new issue, if we see it being flaky in master again!
