### ISSUE TITLE
[Potential Market Issue] Error validating deal published

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3703]
Lotus version: 0.6.0^ after fork

Miners start to get the following error after the fork and bot start to send out deals

```bash
ClientGetDealInfo: {"jsonrpc":"2.0","result":{"ProposalCid":{"/":"bafyreid2wpopid324eu2mjppldzx4xrubuhc7emwjz5z6lss3ukcpzww2a"},"State":26,"Message":"error validating deal published: getting deal pubsish message: blockstore: block not found","Provider":"t015877","DataRef":null,"PieceCID":{"/":"baga6ea4seaqfmx4ymmhcnwr7r2x6sjh6srblkwxjvpxim7gou7sij5gvcyoqqby"},"Size":130048,"PricePerEpoch":"61035","Duration":702831,"DealID":0,"CreationTime":"2020-09-09T11:54:58.885078452Z"},"id":0}
```

some miner id and their logs:
[t015877](https://spacerace.filecoin.io/deals/t015877)
[t02405])(https://spacerace.filecoin.io/deals/t02405)

**Comment by jennijuju** [comment]
some slack thread
https://filecoinproject.slack.com/archives/C0179RNEMU4/p1599663599098200
https://filecoinproject.slack.com/archives/C0179RNEMU4/p1599637557056600
https://filecoinproject.slack.com/archives/C0179RNEMU4/p1599675486164900

**Comment by hannahhoward** [comment]
Likely root cause: the publish CID can change between the time we generate a message and the time the message appears on chain due to gas fee changes. api.StateWaitMsg actually returns the new CID in it's return value, but we are not using it or passing back to markets in providerNodeAdapter.WaitForMessage. While clientNodeAdapter.WaitForMessage is not the cause of this bug, it has the same problem and we should make this change as well.

Proposed solution:
Markets side: Change the callback to WaitForMessage to have a third parameter -- finalMessageCid. At minimum, in markets provider states code, in WaitForPublish, replace the publish CID with the final publish CID when the message appears on chain. Possibly replace CIDs anywhere else we call WaitForMessage.

Lotus Side: in providerNodeAdapter/clientNodeAdapter WaitForMessage call, extract final CID from MsgLookup params (Message param) and pass to call back.
