### ISSUE TITLE
json: cannot unmarshal string into Go value of type crypto.SigType

### ISSUE THREAD

**Issue by mrainyo** [filecoin-project/lotus#3727]
I use curl to call WalletNew to create the address of the wallet. What does crypto.SigType send

**Comment by Reiers** [comment]
Hi @mrainyo 

This is not an issue, its a question.
If you are still wondering about this - please ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

And we will assist you right away ! 

Thank you! 

(_Not transferring to discussion due to old question, author might have gotten a answer._)
