### ISSUE TITLE
some suggestion about troughput

### ISSUE THREAD

**Issue by leviok** [filecoin-project/lotus#3763]
1. winning post task spend a lot of time. omit it will save long time consuming. is it necessary? is it important for security?

2. since lotus is a PoS chain, mining is base on plenty of messages. i think lotus need to support distributed sync. miners can handle the rest(like large machine  or more machines to do sync). user can use light-node or open-api. other full node without mining block can afford sync time more than miner. I don’t have time to have a deep understanding of block validation, now. so i don't know how much logic can be parallel(like some nonce issue?). but i think this maybe help. 

3. this suggestion sounds not good enough, but you can refer to. if sync is not good enough. mining base like use some selection. then mining can drop some block to choose a less messages head. miner who produce it will lose some block weight. but i think it's not a big problem, chain can work with some fork and aggregation finally. i think this can solve some problems caused by extremely high throughput.

hope a better filecoin.

**Comment by whyrusleeping** [comment]
(1) Winning post is pretty important for security, but i'm wondering if we can make it faster by reducing security (this is a question for @nicola )

(2) Light clients are high priority for us to implement, I actually expect to see early versions land in under a month

(3) this is really hard, because of fork protection logic. Miners who mine on two different chains can be slashed (for good reason!).
