### ISSUE TITLE
[Feature Request] Add waitseed to config option when running local devnet.

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3776]
The current `waitseed` default is 75 min and miner think it is too long when running local devnet.

The suggestion is to make it configurable.

**Comment by yongxi-liu** [comment]
in local devnet, waitseed can be set by miners, I think

**Comment by KaptinLin** [comment]
We need 2x nvme disk space for almost 500GB cached files each sector. It's too expensive for miners. Why not reduce 75min to 15min or 30min?

**Comment by ribasushi** [comment]
@jennijuju WaitSeed ( called `PreCommitChallengeDelay` in spec-actors ) is a security-related parameter. It is part of the network consensus, it can not be changed on an individual basis. Only the entire network can lower it.

It was raised due to security concerns here: https://github.com/filecoin-project/specs-actors/pull/657

The ticket can not be implemented as requested, please close if the above explains sufficiently why.

**Comment by yongxi-liu** [comment]
can't it be changed in a local devnet? I setup a 32GB local devnet to test ( sync spend too long ,so I don't  use testnet) , 75mins to wait is too long. @ribasushi

**Comment by jennijuju** [comment]
@ribasushi Updated the topic to add the feature for local devnet - does it make more sense now?

**Comment by jennijuju** [comment]
One workaround is to update `params_debug.go` to

```
// +build debug

package build

import (
	"github.com/filecoin-project/specs-actors/actors/builtin/miner"
	"github.com/filecoin-project/go-state-types/abi"
)
func init() {
	InsecurePoStValidation = true
	BuildType |= BuildDebug

	miner.PreCommitChallengeDelay = abi.ChainEpoch(10) 
}

// NOTE: Also includes settings from params_2k
```

where `miner.PreCommitChallengeDelay = abi.ChainEpoch(10) ` will shorten `WaitSeed` to 10 epoch time (which in debug mode is 4s/epoch)

**Comment by yongxi-liu** [comment]
![Uploading image.png…]()
