### ISSUE TITLE
OOM on sync from scratch

### ISSUE THREAD

**Issue by xtat** [filecoin-project/lotus#3793]
**Describe the bug**
OOM on a 16GB host during new sync. Observed 11g+ resident. 

**To Reproduce**
./lotus daemon

**Version (run `lotus version`):**
Daemon:  0.6.2+git.9e9856bb+api0.14.0
Local: lotus version 0.6.2+git.9e9856bb

**Comment by rjan90** [comment]
Hi @xtat!

Thanks for the report. The issue is outdated, and also the minimum requirements for the Lotus-node is:

`8-core CPU and 32 GiB RAM. Models with support for Intel SHA Extensions (AMD since Zen microarchitecture or Intel since Ice Lake) will significantly speed things up.
`
So it´s expected that it would OOM when syncing with 16GiB RAM

Thanks again !
