### ISSUE TITLE
ERROR	statetree	state/statetree.go:130	loading hamt node bafy2bzacecuiae4vazgmse7hxkoi2kmiirknten3h5xrj7n4bbdw42m67j6go failed: failed to load hamt node: blockstore: block not found

### ISSUE THREAD

**Issue by 815943555** [filecoin-project/lotus#3807]
2020-09-13T19:10:17.735+0800	ERROR	statetree	state/statetree.go:130	loading hamt node bafy2bzacecuiae4vazgmse7hxkoi2kmiirknten3h5xrj7n4bbdw42m67j6go failed: failed to load hamt node: blockstore: block not found
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/home/jack/go_workspace/v070/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.NetworkName: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): load state tree: failed to load hamt node: blockstore: block not found

**Comment by Reiers** [comment]
Hi @815943555 

Thanks for the report. The issue is outdated, and there is not enough information to go on for troubleshooting or reproduce the error. 

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you.

**Comment by RobQuistNL** [comment]
```json
{"level":"warn","ts":"2022-06-14T21:33:01.416Z","logger":"rpc","caller":"go-jsonrpc@v0.1.5/handler.go:279","msg":"error in RPC call to 'Filecoin.ChainGetBlockMessages': failed to load msgmeta (bafy2bzacec62lhkjmliblhkyv72qutlnfvnqh27hbeqlsaygdso4tghzxetiw):\n    github.com/filecoin-project/lotus/chain/store.(*ChainStore).ReadMsgMetaCids\n        /home/master/lotus-source/chain/store/messages.go:219\n  - blockstore: block not found"}
{"level":"error","ts":"2022-06-14T21:33:01.417Z","logger":"statetree","caller":"state/statetree.go:284","msg":"failed to load state tree: failed to load hamt node: blockstore: block not found"}
{"level":"warn","ts":"2022-06-14T21:33:01.418Z","logger":"rpc","caller":"go-jsonrpc@v0.1.5/handler.go:279","msg":"error in RPC call to 'Filecoin.StateGetActor': load state tree:\n    github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).ParentState\n        /home/master/lotus-source/chain/stmgr/read.go:28\n  - failed to load state tree bafy2bzacedgtls4fenajsiozajdwsf57za7573azildeluabmfkqf4dkx4fg6:\n    github.com/filecoin-project/lotus/chain/state.LoadStateTree\n        /home/master/lotus-source/chain/state/statetree.go:285\n  - failed to load hamt node:\n    github.com/filecoin-project/specs-actors/actors/util/adt.AsMap\n        /home/master/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.14/actors/util/adt/map.go:41\n  - blockstore: block not found"}

```

**Comment by Reiers** [comment]
Closed based on lack of information and repro steps.

I read the thread on Slack:
`blockstore: block not found`

The node missing some messages from the pruning - the fix for this in future will be split store so you never will have to prune the chain again. The messages should go away after a while. 

You could active this environment - and it will fetch the missing messages.
`LOTUS_ENABLE_CHAINSTORE_FALLBACK=1`

BUT the environment may cause:

- The sync go much slower
- Its very inefficient with fetching messages
- Put unexpected blocks in your blockstore


I had a bunch of these:

`ERROR	sectors	storage-sealing/states_replica_update.go:267	error in handleUpdateActivating	{"error": "failed to load message: blockstore: block not found"}`

so I used it to recover some stuck UpdateActivating sectors last week.

Again, Im not recommending the environment - its just a quick fix to run the node with it for a couple of hours to fetch the messages. 

We are also looking at creating a more friendly environment to fetch the messages or another solution. 

Thanks for the report!
