### ISSUE TITLE
Add some way to get fault fee info by miner

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#3981]
Perhaps an API endpoint that lists the details of fault fees paid in a certain period?

**Comment by momack2** [comment]
I think this would be really helpful. It would both detail the most recent faults, why they happened, and provide an easy way to calculate the cost for your miner of future similar faults. Ideally, we'd add this info in such a way that chain explorers can also visualize this information more precisely - since many miners use tools like filscout.io to understand their miner's behavior.

**Comment by TippyFlitsUK** [comment]
Hi @arajasek 

This looks like a reminder. Should we close it or keep it open?
