### ISSUE TITLE
UX - See how much time is left on Miner's Wait Deals Delay

### ISSUE THREAD

**Issue by sdm101** [filecoin-project/lotus#4143]
This was a question I asked the Fil-lotus slack channel and Magic6k recommended I open an issue about this.  I was trying understand when one of my sectors in WaitDeals would go on to start sealing in PC1.  If I knew there was enough time, I would pledge another sector and not worry about slowing down my miner or creating a bottleneck by having too many sectors in PC1 at the same time.  

Thanks,

Brian Y

**Comment by Meatball13** [comment]
This is a great idea.  Also would suggest having it show 'x Time left of x WaitDealsDelay Period' or something tlike that so it shows the time left and the original WaitDealsDelay.  Since people can change that on the fly, they could theoretically have sectors that have different WaitDealsDelay values.

**Comment by TippyFlitsUK** [comment]
Hi @sdm101 

Thanks for the report. The issue is outdated. 

If this is a issue in the current release - please open a new ticket.

Thank you !
