### ISSUE TITLE
`lotus client deal` can take price in both interactive or manual mode

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4150]
Right now, `lotus client deal` params can be set all manually or interactively(client doesn't set anything)

However, we want to give client an option to set the price either way so that they can increase the chance for their deal to be accepted by miner by setting a high price, however, does not have to go through trouble for figuring out dataCid, miner, duration.

Proposed update in clientDealCmd:
1) add an option(`--set-price=`) to set price (has to be no param and trigger interactive mode)
or
2)  has ONLY one param and take it as price

**Comment by arajasek** [comment]
I think there's something to this, but I'm not sure what the right thing to do is. One could argue:

- Price shouldn't be settable in non-interactive mode either, it should just be set based on the specified miner's ask. This means hitting "Enter" on `lotus client deal` takes away a lot of $$$ without the client knowing exactly how much, though.
- Price should be configurable in interactive mode too, because you're a generous soul who wants to pay miners more than what they asked for.
- Things are fine as is.

**Comment by dineshshenoy** [comment]
Is the intent something like a max price?  So the client can offer up to $10, but the deal will be at $5 if that's what the miner's ask-price is?  But if the ask is $15, then the deal could not be accepted.
