### ISSUE TITLE
invalid PoSt

### ISSUE THREAD

**Issue by nickboot** [filecoin-project/lotus#4161]
**Describe the bug**
invalid PoSt

**To Reproduce**

2020-10-05T11:25:31.371+0800	ERROR	storageminer	storage/wdpost_run.go:759	estimating gas	{"error": "estimating gas used: message execution failed: exit 16, reason: invalid PoSt

2020-10-05T11:25:32.424+0800	ERROR	storageminer	storage/wdpost_run.go:175	submit window post failed: pushing message to mpool:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).submitPost
        /root/lotus/storage/wdpost_run.go:725
  - GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: invalid PoSt

proof was invalid (RetCode=16)

**Version (run `lotus version`):**
lotus version
Daemon:  0.8.1+git.1ebad94d.dirty+api0.16.0
Local: lotus version 0.8.1+git.1ebad94d.dirty

lotus-miner version
Daemon:  0.8.1+git.1ebad94d.dirty+api0.15.0
Local: lotus-miner version 0.8.1+git.1ebad94d.dirty

**Comment by Reiers** [comment]
**Hi @nickboot** 

**Troubleshooting steps:**

- Check that GPU driver, is correct and working - `nvidia-smi`
- Was your miner busy with PC2/ or C2 under windowPost?
- Are you in sync?
- Does the control address/wallet have enough FIL in it?
- Check if you have any faulty sectors in that deadline
- Check your deadlines partitions with: `lotus-miner proving deadlines`

Run a check of each sector in it with:
`lotus-miner proving check —slow 0`
_(Or 1,2 depending of which deadline failed)_

If you are still having these problems, ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Closing ticket, since its not Lotus issue.
