### ISSUE TITLE
Restore daemon datastore

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4502]
We have `lotus daemon backup` however, there is no way to restore from that back up yet.

Related: #4444 

Something more user friendly would be adding a CLI command  (e.g.  “lotus node repair”.  This would automate the process of rebuilding the chain folder (backup folder, download snapshot, etc))

**Comment by jennijuju** [comment]
We decided to implement `lotus daemon restore` as a restart.

**Comment by dineshshenoy** [comment]
Is the syntax/spec for lotus daemon restore in a different ticket?

**Comment by jsign** [comment]
Last week we got into an unfortunate situation in which the `LOTUS_PATH` folder for a Lotus node was lost, and we had some recent `.bak` file. But since this command isn't available, we couldn't do much about it.

Is there a chance to bump the priority of this CLI command? We were lucky this time that the user of the Lotus node could accept starting from scratch, but feels this was enough of a warning sign that having a way to restore backups would become urgent at any point.

**Comment by dineshshenoy** [comment]
cc: @magik6k
