### ISSUE TITLE
Add `remove` commands within lotus CLI

### ISSUE THREAD

**Issue by pooja** [filecoin-project/lotus#4547]
Today, users directly use `rm -rf` to remove folders within lotus. They do this when they want to re-import a new chain snapshot, when their node isn't syncing properly and they want to start from scratch, when they have tried to connect to a localnet after connecting to test/mainnet, etc. Sometimes, users do things we don't want them to do, e.g. delete ./lotus/datastore and now they have lost all of the information about their saved deals.

Instead of directing users to directly use `rm` or having them figure this out themselves, we should provide a safe method for them to remove the necessary data so that they can proceed with what they would like to do.

One potential flow:
- Include a `lotus remove [path]` command that takes in the path for the data the user would like to delete
- Create a backup automatically for the user
- When the user enters this command, if path leads to an important piece of information, e.g. wallet info, deal info, etc, ask the user in the CLI "You are about to delete [x]. If you need to restore this data, you can run [command] to restore from an automatically-generated backup. Are you sure you would like to continue deleting this data? [y/n]"
- If the user says yes, delete the data.

This way, we can allow users to do what they want to do but within the safe rails of lotus, so they don't accidentally ruin their projects as a result. E.g. check out this [message](https://filecoinproject.slack.com/archives/CRK2LKYHW/p1603304736093100?thread_ts=1603304685.093000&cid=CRK2LKYHW) from a dev to get a sense of some of the pain people experience when deleting data when things aren't WAI.

**Comment by arajasek** [comment]
So I think the problem here is really that we ever need to be deleting the datastore (or anything else). Looking at where we do so in documentation:

- `Compacting the chain data`: This should probably be replaced by some `lotus compact` command that basically does what @pooja describes in this issue (and then imports as needed). We'll definitely still want lots of `--really-do-it` type warnings.
- `Nuking the Lotus data`: This section should be deleted from the main docs, and perhaps moved to some "developer" docs for advanced users.
- `Upgrade with reset`: This should also be deleted from the main docs, it's really not appropriate post-mainnet to be suggesting such action ever be taken.

This list probably isn't comprehensive. If there's other known cases where we find ourselves telling users to delete folders in the $lOTUS_PATH directory, let's discuss them here. It'll probably be the case that some aspect of the UX is quite bad.

**Comment by dineshshenoy** [comment]
@arajasek - I like your direction to be specific on when it's needed.  Let's add tickets to add "lotus upgrade" and "lotus reset" with safeguards.   All 3 of these commands should trigger a backup before continuing forward on the dangerous tasks.

**Comment by dineshshenoy** [comment]
Closing since We have compact/upgrade in different tickets and value of "reset" is minimal.
