### ISSUE TITLE
Random miner crashes

### ISSUE THREAD

**Issue by corviato1** [filecoin-project/lotus#4762]
I occasionally wake up to my miner not working.   I do not know what info I need to provide for devs to help fix this.  Please let me know what info you need and I will share it as quick as possible.

Also the miner would not close unless the daemon is closed first

![image](https://user-images.githubusercontent.com/44780076/98442802-e7829500-20bb-11eb-82af-a967fe5cb475.png)

[sudo dmesg -T _ less.txt](https://github.com/filecoin-project/lotus/files/5505331/sudo.dmesg.-T._.less.txt)

**Comment by corviato1** [comment]
Just aded a txt file of sudo dmesg -T | less

**Comment by jennijuju** [comment]
@corviato1 was your node in sync?

**Comment by corviato1** [comment]
Yes

**Comment by PatrickDeuse** [comment]
i had random miner crashes with 1.1.2 without any traces in the logs too

**Comment by jennijuju** [comment]
maybe related #3940

**Comment by Reiers** [comment]
Hi @corviato1 

Thanks for the report. The issue is outdated, and I dont see random miner crashes anymore. 

If you are still experiencing problems in the [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1) - please open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you!
