### ISSUE TITLE
Can't remove ret-wait status

### ISSUE THREAD

**Issue by vgbluehole** [filecoin-project/lotus#4844]
When I check the sealing jobs I got a not-working ret-wait status.

fa36d8f1c98f  444     0000000000000000000000            C2    ret-wait  n/a
a12ebc8d60ea  646     0000000000000000000000            PC1   ret-wait  n/a
b130f1a9a44a  634     0000000000000000000000            PC2   ret-wait  n/a
667716ff9294  641     0000000000000000000000            PC1   ret-wait  n/a
474667035244  487     0000000000000000000000            PC1   ret-wait  n/a
f9b4f5743848  561     0000000000000000000000            PC1   ret-wait  n/a
c5484fb74c01  550     0000000000000000000000            PC1   ret-wait  n/a

How can I removed that on my sealing jobs?

**Comment by karalabe** [comment]
I also hit this today after restarting my miner but not my worker. I ended up restarting the entire machine to nuke these weirs statuses out as the worker refused to shut down gracefully (couldn't even kill it because it got stuck in a `defuct` status, which is some weird linux state I didn't even know exists).

**Comment by jennijuju** [comment]
@vgbluehole please provide minor info-all and miner logs.
