### ISSUE TITLE
> 我有我的api密钥，我启动了节点，它每晚都关闭，没有任何提示

### ISSUE THREAD

**Issue by EmilyCaoHong** [filecoin-project/lotus#4860]
> 我有我的api密钥，我启动了节点，它每晚都关闭，没有任何提示

I also have this phenomenon。
I have to restart once a day。

_Originally posted by @90hacker in https://github.com/filecoin-project/lotus/issues/4741#issuecomment-723521242_

**Comment by EmilyCaoHong** [comment]
I change to release v1.1.2 is always closed node every night

**Comment by EmilyCaoHong** [comment]
![image](https://user-images.githubusercontent.com/43725403/99210896-f971df80-2801-11eb-8b16-28b4b1c1e517.png)
@90hacker

**Comment by jennijuju** [comment]
Assumably the linked issue was closed by the author since issue was gone or issue is resolved by v1.1.3. So please upgrade to the latest release, and if the issue still exists, please file a new issue with your lotus version and daemon logs, chain datastore size and disk space, we will not be able to investigate the issue without these info.
