### ISSUE TITLE
is there any way to get block miner reward 

### ISSUE THREAD

**Issue by zhp1254** [filecoin-project/lotus#5070]
how can i Statistics every block miner reward

**Comment by weihaipy** [comment]
+1

**Comment by Reiers** [comment]
Hi @zhp1254 

Thanks for the report. The issue is outdated, and not relevant anymore.

If you want Statistics - checkout some of the chain explorers: 

- https://filfox.info/en
- https://filscout.com/zh
- https://dashboard.starboard.ventures/deals

Or run in `lotus-miner info` to get an estimate. 

Thank you !
