### ISSUE TITLE
Terminated sectors still showing in proving deadlines

### ISSUE THREAD

**Issue by shawnp0wers** [filecoin-project/lotus#5164]
**Describe the bug**
When sectors are terminated and removed from a particular deadline, they still show with:
`lotus-miner proving deadlines`

**To Reproduce**
1. Terminate sector which has slipped into another proving deadline
2. Remove sector (same sector) so it no longer shows up when listing sectors
3. Type `lotus-miner proving deadlines` -- sectors still show
NOTE: It does eliminate the actual wdpost, this appears to be cosmetic only, the terminated and removed sectors are not spawning a wdpost for the deadlines in question.

**Expected behavior**
Once terminated and removed, the sectors should no longer appear in the deadline

**Screenshots**
![image](https://user-images.githubusercontent.com/1155853/101681814-be458380-3a30-11eb-8f4d-29a4ec772f2f.png)

**Version (run `lotus version`):**
Daemon:  1.2.2+git.b13226bc2.dirty+api1.0.0
Local: lotus version 1.2.2+git.b13226bc2.dirty

**Comment by jennijuju** [comment]
lotus pulls the onchain information for this cli. that being said, Lotus should expose `[CompactPartitions](https://github.com/filecoin-project/specs-actors/blob/db4db3cc8e3d9013d3080cd387b94ac1d2fe38dc/actors/builtin/miner/miner_actor.go#L1737)` which will clear up the terminated sectors in the miner actor.

**Comment by rjan90** [comment]
Hey @shawnp0wers!

Thanks for the issue-report 😄! Compacting and removing sectors expired/terminated sectors in a proving deadline has been fixed with this: https://github.com/filecoin-project/lotus/pull/8637. There also seems to be a duplicate issue here https://github.com/filecoin-project/lotus/issues/8427, so I´m closing this ticket now, while keeping the other open untill it has been merged.

Again, thanks for the report!
