### ISSUE TITLE
Storage event is too frequent

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#5201]
Right now I have a brand new lotus only doing 5 deals, all of them are in StorageDealCheckForAcceptance state.

When I'm looking at the lotus log there are literally hundreds of lines of output like this one.

` storage event   {"name": "ClientEventWaitForDealState", "proposal CID": "bafyreicdapdiqi6pnpga3hf3aora2dpqrheta6pi3yuuwhhnzuxwpsyawm", "state": "StorageDealCheckForAcceptance", "message": "Provider state: StorageDealTransferring"}`

Is lotus constantly polling the status of all deals in StorageDealCheckForAcceptance state? Is it resource consuming?

**Comment by Reiers** [comment]
Thanks for the report. The issue is outdated, markets have come a long way since the issue was created. 

**Is lotus constantly polling the status of all deals in StorageDealCheckForAcceptance state? Is it resource consuming?**
- No and Its not. 

If you are still experiencing problems in [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1) or have questions - please open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you !
