### ISSUE TITLE
lotus wallet market withdraw does not work

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#5257]
I am trying to recover some funds from my market balance. I see there is some balance in there:
```
lotus state market balance f3sfopz3rgcq5x5eaps5himeybsy36sisrgl7i37wbfs5jyvib73vncg7znbjk2fgj6kwnbomv6fwclk464zva
Escrow: 20.669294826523632896 FIL
Locked: 7.434539598203632896 FIL
```

But when I withdraw, it says insufficient. I have tried all the way to withdraw 1FIL the error messages are the same.
```
lotus wallet market withdraw --from f3sfopz3rgcq5x5eaps5himeybsy36sisrgl7i37wbfs5jyvib73vncg7znbjk2fgj6kwnbomv6fwclk464zva
Submitting WithdrawBalance message for amount 13.23475522832 FIL for address f3sfopz3rgcq5x5eaps5himeybsy36sisrgl7i37wbfs5jyvib73vncg7znbjk2fgj6kwnbomv6fwclk464zva
ERROR: fund manager withdraw error: insufficient funds for withdrawal of 13234755228320000000
```

```
lotus wallet market withdraw --from f3sfopz3rgcq5x5eaps5himeybsy36sisrgl7i37wbfs5jyvib73vncg7znbjk2fgj6kwnbomv6fwclk464zva 1
Submitting WithdrawBalance message for amount 1 FIL for address f3sfopz3rgcq5x5eaps5himeybsy36sisrgl7i37wbfs5jyvib73vncg7znbjk2fgj6kwnbomv6fwclk464zva
ERROR: fund manager withdraw error: insufficient funds for withdrawal of 1000000000000000000
```

**Comment by dirkmc** [comment]
When lotus makes a deal, it starts by reserving funds that are needed for the deal:
`client collateral + storage price per epoch * number of epochs`

The funds are released when either
- the deal is published
- the deal fails

So if you have deals that are still in progress (eg still transferring data) it is not possible to withdraw the funds.

If you don't have any deals in progress and you are still seeing this error, it may be because your local state has got out of sync with the chain state.

**Comment by dirkmc** [comment]
We should change make the error message clearer - the error message should include the amount reserved and the amount available so it's clear to the user why the funds cannot be withdrawn,

**Comment by dirkmc** [comment]
Fixed by https://github.com/filecoin-project/lotus/issues/5257

**Comment by kernelogic** [comment]
Yes that's great. I notice if I import the private key to another clean lotus, I can withdraw all the balance.
