### ISSUE TITLE
"lotus-miner sealing abort" command could not really abort a job

### ISSUE THREAD

**Issue by qiusugang** [filecoin-project/lotus#5262]
**Describe the problem**
The lotus-miner sealing abort bug is too serious. You aborted a job, the jobs list is gone, but the backend is still doing this. It can be observed by looking at the file time in the cache directory.

**Version**
lotus-miner version 1.4.0+git.e9989d0e4

**Comment by Reiers** [comment]
Hi @qiusugang 

Thanks for the report. This is fixed in the latest release.
Please upgrade Lotus.

*Link to latest tags [here.](https://github.com/filecoin-project/lotus/tags)*

Closing ticket.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)
