### ISSUE TITLE
Market escrow balance not show

### ISSUE THREAD

**Issue by KaptinLin** [filecoin-project/lotus#5343]
**Describe the bug**
After transfer FIL to market escrow balance, it's not show correctly. And when publishing deals, it will report error below.

```
deal failed: (State=26) error calling node: publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock client funds: not enough balance to lock for addr xxxxxx: escrow balance 1659454160000000 < locked 1659121360000000 + required 552919640000000 (RetCode=19)
```

**Comment by KaptinLin** [comment]
The balance can be found by using another lotus. See https://filecoinproject.slack.com/archives/C01AZP8BKRQ/p1610141333137100?thread_ts=1610121940.129800&cid=C01AZP8BKRQ
```
Import the wallet at another lotus, you can withdraw all balance.
```

**Comment by dirkmc** [comment]
The error message is saying that it can't publish the deal because the funds required to publish the deal are not available. 

To publish the deal you need to have enough available funds for provider collateral. The provider collateral gets locked until the deal is complete.

In this case the funds required for provider collateral are `552919640000000`
The amount in escrow is `1659454160000000`
The amount of that which is locked (collateral for previous deals) is `1659121360000000`

The available amount is `escrow - locked`
= `1659454160000000 - 1659121360000000`
= `332800000000`

The required amount for provider collateral is `552919640000000`, which is greater than the available amount `332800000000`. So the attempt to publish the deal fails.

Normally lotus protects you against this problem because it prevents you from withdrawing more than the amount required for existing deals, and increases funds whenever you need them for a new deal. However if you move your wallet to a new lotus instance, lotus loses track of the state and cannot protect you.

**Comment by dirkmc** [comment]
Note that there are some improvements to the CLI coming in the next release, so the CLI will give a clearer indication of market balances, and we are also planning to make the documentation clearer:
https://github.com/filecoin-project/filecoin-docs/issues/635

**Comment by KaptinLin** [comment]
We know that, the issue is the available amount didn't show correctly in the provider lotus.

**Comment by dirkmc** [comment]
I'm not sure what you mean when you say "the available amount didn't show correctly". Could you give an example?

**Comment by KaptinLin** [comment]
I didn't know how to explain it as i don't know why it's happening. 

The market balance is not show on origin lotus. It's not on market available, and it's not locked. The FIL just disapper.

But follow the guild on
https://filecoinproject.slack.com/archives/C01AZP8BKRQ/p1610141333137100?thread_ts=1610121940.129800&cid=C01AZP8BKRQ

`Import the wallet at another lotus, you can withdraw all balance.`

The Fil show on another lotus, and we can withdraw them to worker balance.

**Comment by dirkmc** [comment]
> The market balance is not show on origin lotus

What do you mean exactly? What is the output of `lotus client info`?

I'm wondering if you're running into this issue where the funds are reserved because some deals are stuck: https://github.com/filecoin-project/lotus/issues/5257

We recently merged some improvements to the CLI like showing the amount of reserved funds: https://github.com/filecoin-project/lotus/pull/5303

We're also actively working on making data transfers more reliable and giving the user more control over the state of the deal, eg making it easier to cancel deals (so that reserved funds will be released).

Thanks for your patience.
