### ISSUE TITLE
Handling deal proposal failed because of unknown structure member.

### ISSUE THREAD

**Issue by bos162** [filecoin-project/lotus#5601]
**Describe the bug**
The miner sometimes printed error in the miner log saying handling deal proposal failed because of unknown struct field.

**To Reproduce**
1. Run the daemon
2. Run the miner
3. The miner sometimes printed the error by itself.

**Expected behavior**
The miner should be able to handle deal proposals of the current version and all older versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/12178960/108010727-6724d780-6fba-11eb-8ee0-9782e8a5a3db.png)

**Version (run `lotus version`):**
Lotus v1.4.0

**Additional context**

**Comment by dirkmc** [comment]
This bug is occuring because we recently added the `RawBlockSize` to the `DataRef` struct in https://github.com/filecoin-project/go-fil-markets/pull/487
I believe we need to bump the go-fil-markets version and add a migration to make it so this change doesn't break compatibility with previous versions of go-fil-markets.

**Comment by dirkmc** [comment]
Fixed by https://github.com/filecoin-project/lotus/pull/5608
