### ISSUE TITLE
lotus wallet new should support secp256k1-ledger signtype,

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/lotus#5731]
**Describe the bug**
lotus wallet new should support secp256k1-ledger signtype,
lotus wallet new --h
NAME:
   lotus wallet new - Generate a new key of the given type

USAGE:
   lotus wallet new [command options] [bls|secp256k1 (default secp256k1)]

OPTIONS:
   --help, -h  show help (default: false)
but in api_full.go
	// WalletNew creates a new address in the wallet with the given sigType.
	// Available key types: bls, secp256k1, secp256k1-ledger
	// Support for numerical types: 1 - secp256k1, 2 - BLS is deprecated
	WalletNew(context.Context, types.KeyType) (address.Address, error)

**To Reproduce**
1. Run 'lotus wallet new --h'
2. See error,the USAGE don't  contain secp256k1-ledger

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
lotus 1.5.0

**Additional context**

**Comment by rjan90** [comment]
Hey @marco-storswift!

I agree that generally a good UX would be to list all available wallet-types in the usage description. But since ledger-wallet support is disabled by default in the config.toml, listing it in the `lotus wallet new` usage description without additional context could lead users to create that wallet type without enabling it first in the config.

I will keep this issue in mind when writing some notes about the current UX-issues when using a Ledger though. Thanks again for the ticket.

Closing the ticket for now.
