### ISSUE TITLE
Lotus client info command

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#5766]
A `lotus info` command, like `lotus-miner info`, to quickly view high level node status, and aggregate stats in one place

Something like:
```
$ lotus info
Chain: [sync ok] [basefee 1.637 nFIL]
Epoch 123456, chain health 99% (good)
Average block validation time: 2s

Wallets: 10
        Total Balance: 1.1 FIL
        Market Available: 0.1 FIL
Pending messages: past: 0, cur: 1, future: 0

Payment channels: 40
        Locked funds: 0.4 FIL
        Unsettled vouchers: 10 channels, 100 lanes, 0.1 FIL
        Available to collect: 5 channels, 0.2 FIL

Deals: 1285, 2.011 TiB
        Active: 1178, 1.537 TiB
        Transferring: 123, 100 GiB
```

**Comment by frrist** [comment]
The command: `lotus status --chain=true` already has some of this information in its output:
```
$ lotus status --chain=true

Sync Epoch: 74830
Epochs Behind: 16502
Peers to Publish Messages: 41
Peers to Publish Blocks: 41
Blocks per TipSet in last 100 epochs: 3.000000 [UNHEALTHY]
Blocks per TipSet in last finality: 3.228889 [UNHEALTHY]
```

@magik6k or @jennijuju  Would it be alright if this issue was repurposed to extend the `lotus status` command to display the wallet, pending messages, payment channel, and deal bits?

**Comment by jennijuju** [comment]
I think this ticket is asking for a list of client info rather than just chain state info. So add on to what Magik suggested in the o.p, we can also take a look at what info `lotus client` can currently provide and add them to a one cli query that shows all details.

Things I think can be useful to include:
- daemon syncing status
- paych
- how many data is imported locally and total size of stored data (see `lotus client local` and `lotus client stat`)
- how many retrieval deals that's being done/ongoing (see `lotus client list-retrievals`)
- how many storage deals that's being done/ongoing (see `lotus client list-deals` and `lotus client deal-stats`)
- how many ongoing data transfers (see `lotus client list-transfers`)
- storage market client balances  (see `lotus client balances`)
