### ISSUE TITLE
Fix testground tests

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#6023]
It looks like they are failing (This is blocking https://github.com/filecoin-project/lotus/pull/5887)

**Comment by nonsense** [comment]
Lotus deals end-to-end test is working fine, however if there is a high concurrency of deals to a single miner, we are hitting Lotus bugs, that are still not resolved. We'll decide with @dirkmc how to continue, and I will file an issue later on.

For now on, in order to move forward with enabling Testground tests are part of the Lotus release cycle, we could review/merge https://github.com/filecoin-project/lotus/pull/6122 which fixes the deals end-to-end test plan to not hit the concurrency issues.

**Comment by jennijuju** [comment]
@nonsense could you please create a new issue as mentioned above and close this one?

**Comment by gagizoned** [comment]
@nonsense Since [https://github.com/filecoin-project/lotus/pull/6122](6122) is now merged, can we deal with this issue since I believe it can help @magik6k with the test work he has in his scope?

Or we maybe have a separate issue that deals with this topic and this one should be closed as obsolete?

**Comment by nonsense** [comment]
This issue should be closed now.

`deals end-to-end testplans` are now passing.

When they fail it is generally due to three reasons:
1. `lotus-soup/go.mod` needs to be updated. (`lotus-soup` test plan is a separate module from `lotus`).
2. Testground as a service (https://ci.testground.ipfs.team/tasks) is temporarily unavailable.
3. We hit a bug on Lotus.

Addressing these 3 is out of scope of this issue.
