### ISSUE TITLE
Using a colon in the token string for WSS connections fail when using Lotus Lite

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#6111]
We are trying to use Lotus Lite to connect to Infura nodes.  The Infura infrastructure requires a project id/secret to authenticate with the full node using the following syntax:

`export FULLNODE_API_INFO=PROJECT_ID:PROJECT_SECRET:/ip4/filecoin.infura.io `

From @yusefnapora 
I thing whatever lotus is using to parse the wss url doesn't support username:password in the url 
And the token:/ip4/ style addresses seem to assume there will only be one : character...

It appears that https works using the following but not all operations work with https

`export FULLNODE_API_INFO="https://PROJECT_ID:PROJECT_SECRET@filecoin.infura.io"`

Is there a way to connect to wss with a ":" or is there a suggestion for an alternative conneciton method?

cc: @whyrusleeping @terichadbourne

**Comment by magik6k** [comment]
The api info parsing logic lives in https://github.com/filecoin-project/lotus/blob/abc88828f6a7265996397e29d9e82fbbf406d0f0/cli/util/apiinfo.go#L17-L37

**Comment by ribasushi** [comment]
So... this is more involved than I anticipated, it needs a bit of design work.
Infura (what this issue was originally prompted by) is using Basic Auth ( not earer tokens ). Therefore they expect us to open the connection as `"Authorization":"Basic <base64(PROJECT_ID:PROJECT_SECRET)>"`
Currently all we do throughout lotus is `Bearer TOKEN` style.

I am a bit at a loss how do we cram the info about the auth-scheme into`FULLNODE_API_INFO`.

**Comment by TippyFlitsUK** [comment]
New ticket created at https://github.com/filecoin-project/lotus/issues/8385 with updated information.

Closing duplicate  ticket.
