### ISSUE TITLE
Dont panic when calling a method that is not supported by lotus gateway

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6632]
Currently, there are a list of methods thats supported by lotus full node api, but not the lotus gateway apis. So for someone who uses lotus lite and called a methods thats not in lotus gateway, they will get a panic like 
```{"jsonrpc":"2.0","id":0,"error":{"code":0,"message":"fatal error calling 'Filecoin.': panic in rpc method 'Filecoin.: runtime error: invalid memory address or nil pointer dereference"``` .
this should be handled more properly with a clearer error message.

**Comment by placer14** [comment]
I can't seem to reproduce this failure. I've tried a few methods which don't exist as well as explicitly removed some methods and attempted to hit them through a gateway and get the following:

```
$ curl -X POST -i -H "Content-Type: application/json" --data '{ "jsonrpc": "2.0", "method":"asf", "params": [], "id": 0 }' 'http://127.0.0.1:2346/rpc/v0'
HTTP/1.1 500 Internal Server Error
Date: Thu, 22 Jul 2021 21:16:04 GMT
Content-Length: 84
Content-Type: text/plain; charset=utf-8

{"jsonrpc":"2.0","id":0,"error":{"code":-32601,"message":"method 'asf' not found"}}
```

The result is the same for `/rpc/v1` endpoint as well. The 500 error and the body both seem reasonable.

My setup looks like this:
- 2k dev node + miner running w API listening on 127.0.0.1:1234 started w `./lotus daemon --lotus-make-genesis=devgen.car --genesis-template=localnet.json --bootstrap=false`
- lotus-gateway started w `./lotus-gateway --repo=~/.lotus run --listen 127.0.0.1:2346`
- lotus lite node started w `LOTUS_PATH=~/.lotuslite FULLNODE_API_INFO=/ip4/127.0.0.1/tcp/2346/http ./lotus daemon --lite`

I've confirmed the gateway and lite node both become very unhappy when I stop the 2k dev node (returning errors because the wsAPI is unreachable by gateway and lite node detecting websocket close and restarting `listenHeadChanges`).

All of this is to say I'm pretty confident that this is the scenario described above without knowing the exact method which was attempted to produce the above panic.

@jennijuju Can you let me know if this is still happening on `api.chain.love`? Do you know what version of the gateway is producing said panics? Do you know the specific method which might reproduce a panic like above?

**Comment by jennijuju** [comment]
I’m pretty sure it does. So basically try to call something that’s not in Gateway Api interface should do it

**Comment by placer14** [comment]
Here are some failure examples:
```
curl -X POST -i -H "Content-Type: application/json" --data '{ "jsonrpc": "2.0", "method":"Filecoin.StateCompute", "params": [1,[],[]], "id": 0 }' '<URL>/rpc/v0'
```
```
curl <URL>/rpc/v0 -s -X POST -H "Content-Type: application/json" --data '{ "jsonrpc": "2.0", "id":1, "method": "Filecoin.MpoolGetNonce", "params": [ "f1...." ] }' 
```
