### ISSUE TITLE
PricelistByEpoch Technical Debt

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/lotus#6652]
From @Stebalien 
"
PricelistByEpoch has some pretty serious problems and I'm not sure how to cleanly fix them.
- It takes an epoch, not a network version.
- It applies the price-list at the upgrade epoch, instead of after the upgrade epoch. This is off by one.
- The VM calls PricelistByEpoch(currentEpoch)
- Sync/mpool uses the parent tipset's height.
The first step here would be to try to fix the off-by-one and test it around the calico upgrade. If that fails... this is going to be annoying to maintain going forward.
"

Additionally this has made running new auto-gen test-vectors on lotus hard because these assume the latest actors version is valid at height 0 with current price list.  We could remove that assumption during test-vector generation and use the epoch 0 pricelist but this is a step in the wrong direction.

**Comment by ZenGround0** [comment]
I applied the following change fixing the off by one error retroactively:

```diff
diff --git a/chain/vm/gas.go b/chain/vm/gas.go
index c860ce9a0..2201a6eb8 100644
--- a/chain/vm/gas.go
+++ b/chain/vm/gas.go
@@ -130,7 +130,7 @@ var prices = map[abi.ChainEpoch]Pricelist{
                verifyPostDiscount:   true,
                verifyConsensusFault: 495422,
        },
-       abi.ChainEpoch(build.UpgradeCalicoHeight): &pricelistV0{
+       abi.ChainEpoch(build.UpgradeCalicoHeight + 1): &pricelistV0{
                computeGasMulti: 1,
                storageGasMulti: 1300,
 ```

I then synced over the calico upgrade height.  As expected my node experienced a state mismatch error causing the blocks from the first calico tipset (height 265201) to be marked bad.

```
./lotus sync check-bad bafy2bzacecoxdq63inrzyv64pdnfaa5lpv36busleqfll6zr7nbnart6l4jby
1 error occurred:
        * parent state root did not match computed state (bafy2bzacecygfpixj36tp4d7vrmfkksktk7m6adb4lt25yku3hnq3gxgeram4 != bafy2bzacednlept2c32haknb5fm7gw3tvi3bwopjwyig35esfrf4h3caqxg62):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /home/ubuntu/lotus/chain/sync.go:810
```

This means we will have to special case this epoch when switching over to a version based pricelist

**Comment by Stebalien** [comment]
> This means we will have to special case this epoch when switching over to a version based pricelist

Or we can introduce a network version right before calico. Someone, @arajasek?, suggested making network "versions" an enum instead of raw numbers. I.e.,

```go
const (
    NetworkVersionGenesis NetworkVersion = iota
...
    NetworkVersionCalico
)
```

These network versions don't actually appear in the state _anywhere_. As long as the linked version of specs-actors and lotus agree, everything should be fine.

**Comment by Kubuxu** [comment]
I was suggesting with doing away with network versions being integers which would allow us to in future support non-strict ordering of network versions or “injecting” network version in they middle without fear of some integer comparison.

**Comment by Stebalien** [comment]
> Sync/mpool uses the parent tipset's height.

This means that sync/mpool will use the "correct" (old) gas prices. However, from what I can see, switching this to use the same gas prices as we do at execution _shouldn't_ cause the block to be rejected as that would have shown up as a "fine" on-chain.

**Comment by Kubuxu** [comment]
#8163 is only a partial fix

**Comment by jennijuju** [comment]
Yushi suspect the problem should go away when we switch to FVM completely. Revisit if this is still needed for ntwk v16 , or close after the M1 upgrade

**Comment by arajasek** [comment]
Summary from a sync with @Stebalien and @jennijuju today:

- The FVM will _largely_ resolve at M1, since it only has the one price list anyway (and when multiple price lists are introduced, it will definitely be indexed by network version)
- The FVM obviously does not resolve the inconvenience at historical epochs like the Calico upgrade
- Even with the FVM (M1), there is still, albeit unlikely, room for issues:
  - Gas for the VerifyConsensusFault syscall is currently reported by Lotus. If the price for any of the relevant operations for that syscall change, and there's a ReportConsensusFault message at the upgrade epoch, we will create more "poison" blocks
  - There is also the risk that we accept blocks as valid that become invalid when the price list changes. This would basically happen if a message's GasLimit falls below the minimum gas needed for inclusion after the change -- concretely this would need increases in any one of `{onChainMessageStorageBase, onChainMessageComputeBase, onChainMessageStoragePerByte, storageGasMulti}`, or a new formula for `OnChainMessage` entirely. While no such change is planned, the risk exists.
- It would be _really_ nice for this to be some on-chain or "privileged & shared" thing. Duplicating between the various impls and the FVM, and hoping they all resolve to the same PL version is..........unpleasant.

**Comment by jennijuju** [comment]
added a test todo for point 3.b

> Gas for the VerifyConsensusFault syscall is currently reported by Lotus

this sounds..troublesome - what sthe blocker for this to be properly accounted in FVM and lotus calls into that?

point 4 sounds like a really nice M2 or even post M2 thing (like we probably can even hold that in a smart contract - i feel like)
as this ticket itself l feel like this can be a P3 just for tracking.

**Comment by Kubuxu** [comment]
> Gas for the VerifyConsensusFault syscall is currently reported by Lotus. If the price for any of the relevant operations for that syscall change, and there's a ReportConsensusFault message at the upgrade epoch, we will create more "poison" blocks

I don't understand, what is happening there?

**Comment by Stebalien** [comment]
> I don't understand, what is happening there?

VerifyConsensusFault is implemented inside lotus because it requires chain walking. Unfortunately, this means it needs to resolve worker keys, which means it needs to charge gas for this operation.

However... for nv16, we can _probably_ stop charging gas for looking up worker keys, lumping that gas fee into the consensus fault gas fee. This won't be _entirely_ accurate if we start charging per-byte costs on IPLD read (which is the plan), but we have pretty strict limits on the maximum sizes of the objects that can be loaded here.

**Comment by jennijuju** [comment]
We may close this as nv16 will mitigate this issue.
