### ISSUE TITLE
Need to cleanup sector event log

### ISSUE THREAD

**Issue by ohJohanZ** [filecoin-project/lotus#6655]
when I running `lotus-miner sectors status --log id`, there are so many so long event log, how to cleanup the log? Could you add this feature?

**Comment by rjan90** [comment]
Hey @ohJohanZ! I do not think we will support any feature for removing or cleaning up the `sectors status --log <sectorNr>` as it is meant to be a log for debugging if something goes wrong.

Just guessing here since this info was not provided, but the event looping you saw where most likely related to the kvlog-looping we have seen: https://github.com/filecoin-project/lotus/issues/8376 and have fixed. Fixing up issues that causes a lot of event logs are probably the better solution here.

Can you tell more about what events you saw in your `sectors status --log` that made you create this issue?
