### ISSUE TITLE
[Feature Request] lotus-miner data-transfers list show timestamp

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#6785]
Would be great to see timestamp for lotus-miner data-transfers list command. Even just when it's started so we know which transfer happened in approximately on which day.

**Comment by rjan90** [comment]
Closing this issue as outdated on the lotus-miner side of things. This issue is related to the legacy markets code in the Lotus-Miner which will be deprecated.

We recommend users to migrate to [Boost](https://boost.filecoin.io), or similar markets related products for storage providers. In Boost this feature request has been covered, as they have timestamps for data-transfers.
