### ISSUE TITLE
[Mining Issue] Sector recovery not happening

### ISSUE THREAD

**Issue by utgarda** [filecoin-project/lotus#6794]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

Miner sends `SubmitWindowedPoSt`, 7 sectors in faut state, nothing related to recovery is happening.
https://filfox.info/en/address/f0713585

**Describe the problem**
A brief description of the problem you encountered while mining new blocks.

**Version**
```
lotus --version
lotus version 1.10.1+mainnet+git.d920b47e7
```

**Setup**

Same machine for both daemon and miner, using GPU

**Lotus daemon and miner logs**
Please find both logs in comments

** Code modifications **

no modifications

**Comment by utgarda** [comment]
[miner.log.gz](https://github.com/filecoin-project/lotus/files/6841814/miner.log.gz)

**Comment by utgarda** [comment]
[daemon_2k_lines.log.gz](https://github.com/filecoin-project/lotus/files/6841851/daemon_2k_lines.log.gz)

**Comment by Reiers** [comment]
Closing issue, because it didnt find any issues in your logs, DeclareFaultsRecovered messages was sent out.

Also the Storage Provider is no longer active: https://filfox.info/en/address/f0713585

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you !
