### ISSUE TITLE
lotus-miner dagstore list-shards

### ISSUE THREAD

**Issue by Meatball13** [filecoin-project/lotus#7004]
### Checklist

- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] I **am** reporting a bug w.r.t one of the [M1 tags](https://github.com/filecoin-project/lotus/discussions/6852#discussioncomment-1043951). If not, choose another issue option [here](https://github.com/filecoin-project/lotus/issues/new/choose).
- [X] I **am** reporting a bug around deal making. If not, create a [M1 Bug Report For Non Deal Making Issue](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fbug%2CM1-release&template=m1_bug_report_non_deal.yml).
- [X] I have my log level set as instructed [here](https://github.com/filecoin-project/lotus/discussions/6852#discussioncomment-1043678) and have logs available for troubleshooting.
- [X] The deal is coming from one of the M1 clients(communitcated in the coordination slack channel).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.

### Lotus Component

lotus miner market subsystem - storage deal

### Lotus Tag and  Version

```text
lotus version
Daemon:  1.11.1-m1.3.4+mainnet+git.39a0010c7+api1.3.1
Local: lotus version 1.11.1-m1.3.4+mainnet+git.39a0010c7

lotus-miner version
Daemon:  1.11.1-m1.3.4+mainnet+git.39a0010c7+api1.2.0
Local: lotus-miner version 1.11.1-m1.3.4+mainnet+git.39a0010c7
```

### Describe the Bug

Was looking at the new dagstore commands and when I pull a full `lotus-miner dagstore list-shards` all the shards are coming back 'ShardStateAvailalbe' with the exception of one that I'm seeing an error on:

`baga6ea4seaqi44im7hrf74iqn7n7lgeaxykf76qv2vkgdke3goxo64z7qqrgcoi  ShardStateErrored    failed to acquire reader of mount on initialization: mount fetch failed: failed to fetch and copy underlying mount to transient file: failed to fetch from underlying mount: failed to fetch unsealed piece baga6ea4seaqi44im7hrf74iqn7n7lgeaxykf76qv2vkgdke3goxo64z7qqrgcoi: failed to unseal deal 262000: failed to unseal piece from sector 124: unsealing piece: worker UnsealPiece call: context canceled`  

Attempted to run a lotus-miner dagstore  recover-shard for that key and got the following error:

`ERROR: failed to recover shard: failed to acquire reader of mount on initialization: mount fetch failed: failed to fetch and copy underlying mount to transient file: failed to fetch from underlying mount: failed to fetch unsealed piece baga6ea4seaqi44im7hrf74iqn7n7lgeaxykf76qv2vkgdke3goxo64z7qqrgcoi: failed to unseal deal 262000: failed to unseal piece from sector 124: unsealing piece: worker UnsealPiece call: context canceled`

### Deal Status

Don't see any specific errors/issues with deals currently.

### Data Transfer Status

Don't see any specific errors with data transfers currently.

### Logging Information

```text
https://gist.github.com/Meatball13/3d6b3d9cdfa31296e88e43e8c226485c
```

### Repo Steps (optional)

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by LexLuthr** [comment]
Underlying sector "124" does not have an unsealed copy. Dagstore has a lazy init policy so sectors are not unsealed unless a retrieval deal asks for the data. 

You can trigger a retrieval deal and that will initialise the shard after UNS.

**Comment by rjan90** [comment]
Closing this issue as outdated on the lotus-miner side of things. This issue is related to the legacy markets code in the Lotus-Miner which will be deprecated.

Boost has been working on designing, building, and testing a new Local Index Directory which will replace the dagstore which this issue is related to. X-posting the message from their announcement channel:

:mega: **Coming soon: Yugabyte database for the new Local Index Directory** (LID)  :mega: **
As you may know, we have been working on designing, building, and testing a new Local Index Directory which will replace the dagstore. Many of you have reported problems with the dagstore, and migrating to use LID will help resolve these issues. The LID introduces a horizontally scalable backend database for storing the data - YugabyteDB. We would love to get your input and feedback on these changes - feel free to raise them in [Boost discussion](https://github.com/filecoin-project/boost/discussions) or reach out in this slack channel.

**How this benefits SPs!**
- We are no longer relying on the dagstore!
   - Increased visibility into the state of your sectors and indexes
- Improved coordination between Lotus and Boost (Lotus will also leverage YugabyteDB)
   - built-in UI and admin panel for YugabyteDB for easy management
- Enables scalability for SPs storing client data.
   - Read more details on how this works: https://boost.filecoin.io/experimental-features/local-index-directory
   - Ensuring your data can be reliably retrieved will become increasingly more important as the ecosystem continues pushing on retrieval incentives and reputation systems, both of which have teams actively working on them.

**What’s next?**
- The Boost team has completed migration of our two production miners to LID, and we will be monitoring for any issues that come up. :bar_chart:
   - We will work with other early adopter SPs and Lotus TSEs to try this out! :tada:
- We are working on documentation and migration tools, and will announce when it is ready for all SPs to migrate to LID.
- Again, we’d love to hear directly from you. Please let us know your input and feedback in [Boost discussion](https://github.com/filecoin-project/boost/discussions), or reach out in [#boost-help](https://filecoinproject.slack.com/archives/C03CKDLEWG1).
