### ISSUE TITLE
high memory utilization in go-graphsync

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#7077]
### Checklist

- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] I **am** reporting a bug w.r.t one of the [M1 tags](https://github.com/filecoin-project/lotus/discussions/6852#discussioncomment-1043951). If not, choose another issue option [here](https://github.com/filecoin-project/lotus/issues/new/choose).
- [X] I **am** reporting a bug around deal making. If not, create a [M1 Bug Report For Non Deal Making Issue](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fbug%2CM1-release&template=m1_bug_report_non_deal.yml).
- [X] I have my log level set as instructed [here](https://github.com/filecoin-project/lotus/discussions/6852#discussioncomment-1043678) and have logs available for troubleshooting.
- [X] The deal is coming from one of the M1 clients(communitcated in the coordination slack channel).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.

### Lotus Component

lotus miner market subsystem - storage deal

^^ Selected "lotus miner market subsystem - storage deal" because I had to select one. We should allow multiple options here, because it's not clear if this is storage only, retrieval only, or both.

### Lotus Tag and  Version

```text
m1.3.5.
```

### Describe the Bug

High memory utilization leading to eventual process crash. Heap profile taken by the memory watchdog when surpassing emergency levels. Shows extreme retention at graphsync layer. Suspected artefact from logging that we introduced in the last releases to aid debugging.

![image](https://user-images.githubusercontent.com/1101242/129488077-85e29c38-dbe0-422e-89e0-988f00cc5d7b.png)

### Deal Status

N/A

### Data Transfer Status

N/A

### Logging Information

```text
N/A
```

**Comment by aarshkshah1992** [comment]
@raulk @hannahhoward Attaching some more heapprofiles here

market/.lotusmarkets/heapprof/2021-08-18T04:33:44.549532467Z.heap

**Comment by aarshkshah1992** [comment]
- The heapprofile leads me to suspect that it's because of the blocks we store in-memory in the unverified blockstore. The received Graphysync messages will be retained till we keep the block data in-memory. Note that the consumer of those in-memory blocks i.e. the IPLD traverser submits consume messages via the same event loop that's also used to add incoming blocks to the in-memory blockstore which can lead to contention here.
- Also, Estuary has a problem where it's datastore is missing some blocks for storage deals. This can exacerbate the problem as we will buffer the other blocks till the receiver sends a Graphsync cancel to the responder i.e. Estuary after noticing that a block is missing (i.e. IsKnownMissingLink=true). My understanding of the code tells me that we do send a Cancel here to the responder when we notice that a block is missing. Please can you confirm this ? If not, that's a big problem because the Graphsync responder traversal has been coded to keep sending the other  blocks even if they don't have some of the blocks (by singalling continuation using the traverse.SkipMe error) .
- To confirm the hypothesis that the in-memory unverified blockstore is the culprit here, I've raised https://github.com/ipfs/go-graphsync/pull/201 with some logging around the size of the data that's being kept in the unverified blockstore. We can draw conclusions once we've had the chance to run that PR on some miners and get back stats.

**Comment by hannahhoward** [comment]
WIP Solution: https://github.com/ipfs/go-graphsync/pull/204

**Comment by aarshkshah1992** [comment]
Should be solved by https://github.com/ipfs/go-graphsync/pull/204.
