### ISSUE TITLE
automatically export helpful info needed for debugging upon crash

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7315]
This can be a shed cmd or some feature miner can enable in the configuration. The goal would be auto-saving all the information can be used for debugging whenever there is a node crash, hang, error and so on.  Info to save can be similar to `lotus-miner info all`, logs, goroutines, dmesg. etc.

**Comment by placer14** [comment]
Putting some concreteness around this, I'm going to use a panic as the most obvious trigger for this behavior. I will write it such that it can be called from anywhere should we decide to add this to outher high-value failure cases.

Will start with a stacktrace, goroutine, and journal+log snippet from prior $DEBUG_PANICNET_LOGLOOKBACK=1m (or something) and we can go from there.

**Comment by f8-ptrk** [comment]
the journal does what the journal does. people just need to know about it in the first place. it's kind of a hidden feature. it rotates properly upon restart already i think

maybe have a debug log that get rotated ever 2nd restart or some like that. 

i wouldn't connect this feature to the normal log people are running

**Comment by f8-ptrk** [comment]
logs connected to a crash can date back hours @placer14 

thats my main concern with $DEBUG_PANICLOG_LOOKBACK=1m

**Comment by gh3990** [comment]
maybe have a little separation in there like :

lotus-miner info all (for everything mentioned above by Jenn)
lotus-miner info WinPost (for everything related to troubleshooting WinPoST)
lotus-miner markets info all (everything relate to the market node)
lotus-miner tech info all (will also take env, storage config, miner config, api config, network config)

just an idea :-)

**Comment by TippyFlitsUK** [comment]
I would opt top have this as a manually triggered additional command rather than something that is fired automatically.

**Comment by Meatball13** [comment]
Yeah, agreed that it might be nice to have it manually triggered.

**Comment by placer14** [comment]
@f8-ptrk 
> the journal does what the journal does. people just need to know about it in the first place. it's kind of a hidden feature. it rotates properly upon restart already i think

The journal eventually rotates that away if you're not looking for the panic info at that moment. We're trying to make it easy for operators to gather this information easily. The journal is still going to journal and we'll snapshot the last N lines for this report to save for later, as needed.

> i doubt it makes sense to keep extensive logs in memory just to write them out in case of a crash
I'm leaving the logs alone expecting that will already be stored by most rudimentary deployments. The example above keeps nothing in memory until triggered (and then allocs the bare minimum in case the panic is due to OOM conditions).

> thats my main concern with $DEBUG_PANICLOG_LOOKBACK=1m

Good point. I made it [number of lines](https://github.com/filecoin-project/lotus/pull/7341/files#diff-3c77b768688af24630531611dce1d0271ad9f14cbbb2b4fc893ffaa5fec406a4R25). Not ruling out the envvar, but still unsure how we'll expose this.

> lotus-miner info all (for everything mentioned above by Jenn)
> lotus-miner info WinPost (for everything related to troubleshooting WinPoST)
> lotus-miner markets info all (everything relate to the market node)
> lotus-miner tech info all (will also take env, storage config, miner config, api config, network config)

@gh3990 If you let me know where I can find some of this stuff, we can see how/where it makes sense to add it. I'd also be curious how you would use the information you mention.

> I would opt top have this as a manually triggered additional command rather than something that is fired automatically.

> Yeah, agreed that it might be nice to have it manually triggered.

@TippyFlitsUK @Meatball13 How would you know when to call the command? Would you call this after you noticed a failure? Do you have some system setup to call it. I expect we'd be using this to catch unexpected panics and firing automatically will help us keep the state of the node before it dies.

Thanks for the feedback! Keep it coming.

I made a first stab to capture some node state. This report will perserve a heap+goroutine pprof dump, a snippet of the last N lines of the journal, and the stacktrace of the panic. If there are other things which get lost once the node dies which are helpful for post-mortem debugging, it could be valuable in this function.

I'm also not sure if this is the best place to catch, but we can figure that out. https://github.com/filecoin-project/lotus/pull/7341

**Comment by placer14** [comment]
I've added envvars to many of the config values. 

Re: manually triggerable CLI command: I don't think this is going to be the thing we trigger manually since it requires the binary runtime to be the context of these panic reports. We can consider a manual trigger to gather environment information as a separate issue. Let's try to put some clarity around how such a utility would be used and what data we think it should capture. I'll create an issue and we can explore this there.

Keep the feedback coming!

**Comment by placer14** [comment]
Please direct further feedback and followup considerations to https://github.com/filecoin-project/lotus/issues/7358. 🤝

**Comment by placer14** [comment]
Some of this was delivered in https://github.com/filecoin-project/lotus/pull/7341. Closing this as resolved with the above issue for fresh steps forward.
