### ISSUE TITLE
Retry PSD with valid deals if the message failed

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7368]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

Currently, if a PSD is failed, SP cannot re-publish the valid deals in a new msg - however, we should do that to improve deal-making experience for both sides.

**Comment by nonsense** [comment]
@jennijuju could you clarify this ticket? Is this about retrying deals that were batched together with a failing deal?

AFAICT when we have 1 deal in a PSD message, and it fails, it is not a transient error, and there really is nothing to retry. If we have N deals and a PSD message fails because of 1 bad deal, then it makes sense to still retry the N-1 deals, but this obviously is not how Lotus works today, and something worth improving. WDYT?

**Comment by jennijuju** [comment]
> @jennijuju could you clarify this ticket? Is this about retrying deals that were batched together with a failing deal?
> 
> AFAICT when we have 1 deal in a PSD message, and it fails, it is not a transient error, and there really is nothing to retry. If we have N deals and a PSD message fails because of 1 bad deal, then it makes sense to still retry the N-1 deals, but this obviously is not how Lotus works today, and something worth improving. WDYT?

This is exactly for the later case!

**Comment by nonsense** [comment]
@jennijuju sorry, but having looked at the code, this is still confusing.

We already validate and publish only deals that are valid, done at https://github.com/filecoin-project/lotus/pull/7234 . So I assume this ticket is about retrying PSD after it has actually failed, which means that it passed simulation, only valid deals were included because of simulation, but even so - the PSD failed for some reason.

I am trying to understand why a PSD would fail after simulation, before trying to address this.

**Comment by nonsense** [comment]
Having spoken to Lotus folks, we decided to close this one in favour of https://github.com/filecoin-project/lotus/issues/7102

Basically it is not obvious when an error is transient and when we need to retry, so for the time being having a manual retry mechanism is a good first step.
