### ISSUE TITLE
Integrate proof v10.0.0

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7388]

**Comment by cryptonemo** [comment]
FFI PR is up here: https://github.com/filecoin-project/filecoin-ffi/pull/204

CI should be green except for the 2 blst/pairing tests (which no longer exist and should be removed by someone with FFI settings powers).

CUDA Doc link is here: https://github.com/filecoin-project/filecoin-ffi/tree/update-proofs-v10-0-0#experimental-cuda-build-support

In short, if people want to try out CUDA support (instead of opencl), they can use `FFI_USE_CUDA=1`

**Comment by jennijuju** [comment]
> removed by someone with FFI settings powers

who is this someone?

**Comment by cryptonemo** [comment]
> > removed by someone with FFI settings powers
> 
> who is this someone?

Honestly, I'm not sure (but it's not me).  Maybe Magick, or Dig?

**Comment by magik6k** [comment]
^ Updated the CI rules

**Comment by cryptonemo** [comment]
> ^ Updated the CI rules

Thank you!

**Comment by magik6k** [comment]
https://github.com/filecoin-project/lotus/pull/7420

**Comment by cryptonemo** [comment]
Some feedback applied: https://github.com/filecoin-project/filecoin-ffi/pull/205

**Comment by cryptonemo** [comment]
> Some feedback applied: [filecoin-project/filecoin-ffi#205](https://github.com/filecoin-project/filecoin-ffi/pull/205)

I don't know that this is blocking, FYI, but would be nice to get in if/when working
