### ISSUE TITLE
FSM changes that we need to make for Snapdeals implementation

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/lotus#7515]
We need to change the pipeline in order to implement changes for SnapDeal

**Comment by BlocksOnAChain** [comment]
This issue will be used to track FSM changes which are "nice to have" by 22nd November

**Comment by ZenGround0** [comment]
## Description 

The lotus-miner binary's proving logic is organized into roughly two layers, the FSM which handles chain and deal subsystem interaction and implements configurable operation logic, and the sector storage layer which manages sector data and associated files, calling into the proving ffi as needed.

This issue is to add FSM support to the lotus miner for recording all of the application logic around doing snap deals replica updates.  This means crafting new states and a path through them in the FSM taking sectors from empty to provably containing snap deals and recording this on chain.  

## Done Criteria

* Most fundamental criteria: one integration test checking that snap deals can be added in the happy path
* A basic methodology exists for deals to come into the system and be added to snap deals.  The basic requirement is that storage providers be able to mark sectors as cc upgrades as exists today to accept snap deals.  Debate about further scope that people want should happen in another issue.
* The FSM guides sectors through the pipeline from 1) marked for snap deals 2) data added 3) sector-storage system performs update, proof and returns proof data 4) communication with the chain 5) cleanup of old sector data.
* Of course we need to handle error cases too

## Dependencies
* Not a strict dependency but this logically flows after: https://github.com/filecoin-project/lotus/issues/7525

## Ongoing Work

No PRs open yet, though I have ideas stuck in my head from before a data loss incident :)
