### ISSUE TITLE
sector-storage supports snap deals

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/lotus#7525]
This issue will be used to track our design + implementation efforts to create a more flexible way to sector storage for SnapDeals

Direct DRI to deliver will be: 
@magik6k will do the design + @ZenGround0 will be involved
- @ZenGround0 will do the implementation after we approve the design

**Comment by jennijuju** [comment]
In case the `UpdateReplica` message fails, lotus should be able to keep the to-be-upgrade CC sectors and reuse it for new deals (we probably should keep the copy of the data for the original CC sectors until the upgrade is confirmed to be successful.

**Comment by ZenGround0** [comment]
FYI Currently I'm adding a new file type for updated replicas and their caches.  This won't generalize too nicely with multiple snap deals updates but it should be enough for the next update we expect to release.  Will link a draft PR soon.

**Comment by ZenGround0** [comment]
## Description

The lotus-miner binary's proving logic is organized into roughly two layers, the FSM which handles chain and deal subsystem interaction and implements configurable operation logic, and the sector storage layer which manages sector data and associated files, calling into the proving ffi as needed.

This issue is to add snap deals replica updating support to the sector-storage part of this stack.  It requires integrating the FFI, adding filetypes, storage manager, scheduler and worker support for doing these ffi operations and storing relevant files and  presenting an interface for the FSM

## Done criteria
1. There is a test that runs the sector-storage manager snap deals replica update function on a real sealed sector and successfully validates the proof of update.  To start it should run on 2k sectors.  This test will then be handed off to people with good hardware and tested on all sector sizes.
2. There is an interface for the FSM to call into sector storage.  This will be a thin wrapper around the manager call covered by the above test.

## Dependencies

This PR needs the following things done before it can be completed
- [x] change specs-storage interface: https://github.com/filecoin-project/specs-storage/pull/17
- [ ] integrate ffi backend into lotus: https://github.com/filecoin-project/filecoin-ffi/pull/208

## Ongoing work

https://github.com/filecoin-project/lotus/pull/7615

**Comment by jennijuju** [comment]
closed by #7615
