### ISSUE TITLE
Pond - API not running

### ISSUE THREAD

**Issue by morrigan** [filecoin-project/lotus#829]
Steps to reproduce:

1. ./pond run
2. open web and click Open pond
3. Spawn node
4. Spawn storage miner
5. Storage miner initializing....

Result: 
Storage miner not created, got uncaught promise with error `"API not running (no endpoint)"` in Console.

Update:
6. Refresh page and there is a storage miner window which seems like working!

**Comment by magik6k** [comment]
This is caused by https://github.com/filecoin-project/lotus/blob/91bb233efb07fea33f80085550ec33a2a6a50a3d/lotuspond/spawn.go#L197, and the fact that by default storage miner in checking parameter files now, which takes a bit of time.

The best workaround is to use pond with debug binaries - `make debug && ./pond run`. This can probably can be fixed be waiting for the api endpoint to appear in that function.

**Comment by whyrusleeping** [comment]
We are deprecating support for pond for now. So i will be closing this issue for now
