### ISSUE TITLE
simulate all methods against builtin actor 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#8483]
while the test coverage continues to increase, we also have a better understanding whether  the builtin actor works fully with the current mainnet, and will continue work with after nv16 migration

Currently, there are two potential ways we can do that:
- lotus-sim: is a tooling  that tests how the  VM and actors work as  the network grows  & network upgrade. (see more in https://github.com/filecoin-project/lotus/pull/6406 - steb has volunteered to give a walk through on how this thing works if you wanna explore this option); to hopefully catch state mismatch, you will need to do some tweaking to run both VM
- creates a series of lotus-shed tooling for constructing the messages and send it to the chain

**Comment by arajasek** [comment]
I think lotus-sim is good for seeing how things scale, but doesn't capture the full range of possible messages. I think we should also do the following against a testnet:

- Make a deal (`lotus client import`, then `lotus client deal`), perform a PAID retrieval for the data (tests payment channels)
- Invoke CompactPartitions, which is rarely used on mainnet
  - This probably requires adding some large number of sectors, and then terminating (say) 50% of them.
  - Also definitely needs a shed command, because nothing invokes this yet afaik
- Dispute WindowedPost
  - Run a lotus disputer
  - Either write a shed command that intentionally sends a bad PoSt, or hack the Lotus miner to send garbage posts
  - Check that the disputer catches this bad post, and successfully disputes it
- Report a consensus fault successfully:
  - Easiest way to do this is to take the worker key of a miner that has power in the network
  - (Write a shed command to) "Sign" 2 blocks at the same height -- easiest way to do that is probably to find a block already mined by the miner, and sign a slightly different second block based on that
  - Marshal these signed blocks into the params for a `VerifyConsensusFault` message, and send it (any sender)
- Make a verified deal (requires access to the VRK, creating verifier & verified client)
- Snap a deal
- ExtendSectorExpiration for any sector

**Comment by geoff-vball** [comment]
Calling `paych collect` seemed to hang when called by the miner on the cli, the message was correctly processed. I'll re-run this test to see if it's a real issue.

**Comment by geoff-vball** [comment]
Running a disputer did not seem to catch an invalid windowed-post. Calling `dispute` from the cli also errored out for some reason. Am going to investigate further when caterpillar net is reset.

**Comment by geoff-vball** [comment]
Issue found here https://github.com/filecoin-project/lotus/issues/8636

**Comment by geoff-vball** [comment]
Isuee found with snapping deals: https://github.com/filecoin-project/lotus/issues/8703
