### ISSUE TITLE
`encountered an I/O error: not on curve` and WindowPoSt retry

### ISSUE THREAD

**Issue by askender** [filecoin-project/lotus#8575]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

```
2022-05-02T04:16:01.402+0800	ERROR	storageminer	storage/wdpost_run.go:648	error generating window post: encountered an I/O error: not on curve
2022-05-02T04:16:01.402+0800	ERROR	storageminer	storage/wdpost_run.go:105	runPoStCycle failed: running window post failed:
2022-05-02T04:16:01.402+0800	ERROR	storageminer	storage/wdpost_run.go:49	Got err running window post failed:
```
Sometimes when gpu got a problem(`encountered an I/O error: not on curve` ?  ),  and it will miss the WindowPoSt and lost all power, I think it would be better to retry use the CPU to try the WindowPoSt again.
Or there should be a document about how to only use CPU to do WindowPoSt.   
Thanks.

**Comment by rjan90** [comment]
Hey @askender 😄 Thanks for the issue-report - and as you noted, encountered an I/O error: not on curve, is usually a GPU or disk-related issue.

I agree that falling back to CPU could be ideal in certain situations, but that also means the lotus-miner machine needs to have a very powerful CPU (at least if the partition is full). And for machines that do not have that, you would probably see even more consequential errors if it fell back to the CPU.

[windowPoSt-workers](https://lotus.filecoin.io/storage-providers/seal-workers/post-workers/#launching-post-workers) should allow for retries of failed windowPoSts on other wdPoSt-workers. So I think that is a better way forward then explicitly retrying on the CPU. If you still think that a fallback-option is needed, please file an _Feature Request_ detailing the feature.

Because retries are possible with windowPoSt workers, I will close this issue fore now. If you still think that a fallback-option to CPU is needed, please file an _Feature Request_ detailing the feature.

Thanks again for the report! 😄

**Comment by askender** [comment]
Thanks!   Some discussion here:  https://filecoinproject.slack.com/archives/CPFTWMY7N/p1651489743973999 
I am trying to figure out why `encountered an I/O error: not on curve` occur,  someone said it maybe related to the `sealing-disk(s)`. 
I will still test about `GPU or disk-related issue` and found the detail reason about it and report it here. 

I remove `and WindowPoSt retry` in title, and tweat the title.
