### ISSUE TITLE
 Builtin Actor Bundling Strategy

### ISSUE THREAD

**Issue by vyzo** [filecoin-project/lotus#8625]
For NV16 and beyond, where we live in an fvm world, we need an effective mechanism for bundling and loading builtin actors manifests.

## State of Affairs
The current approach, in #8493, is to 
- embed the appropriate v8 bundle at build time, selected by build tags for the various networks
- have the fvm directly embed v7/v6 bundles.

The bundles are downloaded at build time, using the release tag from github.

This is problematic for two reasons:
- it doesn't scale as we move to future network versions, where we'd have to bundle builtin actors for every supported version
- it conflicts with the plan to move to a single binary for all networks (see #8158)
- it requires an unwanted dependency of fvm to actors, just to embed older network version support.
- it requires an ugly environment variable hack to load bundles for tests in DI.

## Dynamic Bundling Proposal
In order to address these issues and sever the dependency from fvm to the older actors bundles, we propose to dynamically fetch and load bundles at start up, using the release tag on github.

More specifically:
- embed the release tags for each builtin actors version (v7, v8, and beyond).
- when the lotus daemon starts, fetch the appropriate bundle (for the selected network) and persist in the `.lotus` repo, and then load into the blockstore once (not each and every time).
- pass the appropriate manifest to the fvm for v7, which is unnecessary for v8 as the manifest is in the system actor state to sever the dependency.

For tests, we propose to fetch the bundle in a fixed location (somewhere in /tmp) so that it can be cached from CI and reused for subsequent test runs.

One minor annoyance/difficulty is that the cli and lotus miner init also need to load the manifests so that they have access to the actor code CIDs; this currently happens using an in memory blockstore; this can continue, but instead of using embedded bundls, use the bundles as found in the repo and fetch dynamically as required.

**Comment by raulk** [comment]
A few notes on requirements:

- There's already a similar precedent of the download-on-startup flow today: the proof parameters. We use https://github.com/filecoin-project/go-paramfetch/, and we should probably unify with that to avoid entropy in the codebase?
- We do need to provide an offline option. Not because daemons won't be having Internet connectivity (we can take that for granted, otherwise they wouldn't be able to participate in the network). However, some nodes in some parts of the world don't have access to GitHub (usually due to censorship). This was a problem with proofs, which have/had to be delivered through region-specific data centers (painful).
	- Should probably make the flow "download if not embedded" (if the VFS returns not found).
- Need to provide an option to test with a local bundle for development.
- How do the testing bundles get loaded in this design?

Requested sequence for implementation, each in a separate PR:

1. Get rid of builtin-actors dependency in filecoin-ffi. (P0)
2. Get rid of bespoke env variable magic for v7 manifest. (P0)
3. Implement the runtime loading. (P1)

My rationale is to hedge against not being able to fully implement and test everything before feature freeze EOW. If so, I really want (1) and (2) implemented -- these are non-optional!

**Comment by raulk** [comment]
Implementation concern: I think we should separate the _specification_ of "locked" bundle releases for every actors version from the _selection_ of which ones are necessary to provision.

Basically we need an API:

```go
func EnsureActorsBundlesLoaded(version... actors.Version) error
```

That components can call throughout their lifetime to ensure their dependencies are satisfied. We call it on system startup and on migrations.

Note that we only ever expect to use two actor versions at a time, but for historic traceability, the bundle specification file (`bundles.spec`) should include the locked hashes for every historical actor version.

## Implementation notes

In terms of design, I would imagine we have two components:

1. BundleSpecification (embeds `bundle.spec`), offers a release resolver method: `GetReleaseForActor(version actor.Version) (hash string)`.
2. BundleLoader, an interface with two implementations:
	1. EmbeddedBundleLoader, used for offline builds where we're embedding the bundle
	2. OnlineBundleLoader (default), downloads the bundle from GitHub.

`BundleLoader` offers a single method:

```go
LoadBundle(blockstore Blockstore, hash string, network string) (manifest cid.CID)
```

**Comment by vyzo** [comment]
See also https://github.com/filecoin-project/lotus/pull/8642#issuecomment-1127546987

**Comment by travisperson** [comment]
This issue covers a few topics and I wanted to provide some thoughts / input across the general fvm integration into lotus from my experience developing deployment patterns for lotus networks through the development cycle of lotus and Filecoin proofs.

The Filecoin ffi and Filecoin proofs are analogous to the fvm and builtin-actors I think. The builtin-actors are may require additional flexibility, but I think proofs provide a nice base.

Filecoin FFI

- The Filecoin ffi is a submodule of the lotus project, and when lotus builds its dependency by default the libfilcrypto is downloaded from Github using the submodule HEAD.
- The ffi can also be built locally by setting the `FFI_BUILD_FROM_SOURCE` env.

FIlecoin Proofs Parameters

- Filecoin proofs are configured by lotus through a [json file](https://github.com/filecoin-project/lotus/blob/master/build/proof-params/parameters.json) that gets bundled into the lotus binaries and is updated when new proofs are released.
- Lotus provides tooling through various clis (`lotus fetch-params`, `lotus-miner fetch-params`, `lotus-shed fetch-params`) to support downloading the parameters prior to daemon startup.
- The params are stored in a default location, but the location can be changed using the `FIL_PROOFS_PARAMETER_CACHE` env.
- Proofs are fetched over http but the targeted IPFS gateways can be changed done via the `IPFS_GATEWAY` env which allow for local caching.

This setup has seem to work well and is worth considering following a similar pattern for fvm and builtin-actors. While params are not fetch over IPFS directly, the presence of the CID for the proofs provides IPFS compatibility and flexibility for lotus operators.

**Comment by Stebalien** [comment]
So, we've run into a few issues here:

1. It depends on GitHub at runtime, which won't work in places where GitHub is blocked.
2. It depends on GitHub tags not changing (not secure, hard to debug). Hard-coding CIDs fixes this, mostly.
3. It downloads bundles synchronously in all lotus binaries, on _init_.
    - Stalls the client with no feedback. Simply running `./lotus --help` will hang on a network request. We've already had one user (besides me) hit this.
    - Could fail, leading to a panic.
    - Doesn't work offline.
    - Applies to everything, even shed commands.

It also turns out that the initial issue with building in the actors aren't necessarily true:

> it doesn't scale as we move to future network versions, where we'd have to bundle builtin actors for every supported version

Each bundle can compress to around 500KiB. We'll move to on-chain deployment of system actors before this becomes a real issue. I.e., once we start deploying system actors via messages, the "upgrade" just needs to deploy a new manifest (which will be tiny).

> it conflicts with the plan to move to a single binary for all networks (see one binary, multiple networks #8158)

The compress _very_ well together. After packing all of our current bundles into a tar file and compressing it with zstd, I get a  700KiB file.

> it requires an unwanted dependency of fvm to actors, just to embed older network version support.

At these sizes, we can check-in the compressed bundle into the source (same as we do with the genesis file CAR files).

**Comment by Stebalien** [comment]
All the bundling work has been completed.
