### ISSUE TITLE
BUG: too much memory released (during markets node start)

### ISSUE THREAD

**Issue by Shekelme** [filecoin-project/lotus#8632]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
lotus-miner version 1.15.2+mainnet+git.518dc962e
```

### Describe the Bug

I see the BUG: too much memory released message during markets node start. In spite that [this should be fixed already](https://github.com/filecoin-project/lotus/pull/7969).

### Logging Information

```text
2022-05-10T18:08:57.590+0300    WARN    rcmgr   go-libp2p-resource-manager@v0.2.1/scope.go:102  BUG: too much memory released
```

### Repo Steps

Start markets node and observe Go-log during startup process.

**Comment by vyzo** [comment]
cc @marten-seemann

**Comment by j1v** [comment]
`2022-05-11T15:36:43.180+0300	WARN	rcmgr	go-libp2p-resource-manager@v0.2.1/scope.go:102	BUG: too much memory released`

Just adding that it doesn't look that it's related to markets startup. I'm seeing those long after restart ( a couple of hours later )

**Comment by j1v** [comment]
> whats the libp2p version in your build?

```
~$ lotus-miner version
Daemon:  1.15.2+mainnet+git.518dc962e+api1.5.0
Local: lotus-miner version 1.15.2+mainnet+git.518dc962e
```

**Comment by hyunmoon** [comment]
`2022-05-12T00:23:48.284+0900	WARN	rcmgr	go-libp2p-resource-manager@v0.2.1/scope.go:102	BUG: too much memory released
2022-05-12T00:23:48.305+0900	INFO	builder	node/shutdown.go:44	miner shut down successfully 
2022-05-12T00:23:48.305+0900	WARN	builder	node/shutdown.go:47	Graceful shutdown successful`

My miner also crashed due to this issue.
Roll back to 1.15.1?

**Comment by marten-seemann** [comment]
Hi guys, go-libp2p maintainer here 👋

Can you please record a rcmgr log by setting the LOTUS_DEBUG_RCMGR environment variable?

**Comment by vyzo** [comment]
Note that this cannot cause a crash.

**Comment by Shekelme** [comment]
> Can you please record a rcmgr log by setting the LOTUS_DEBUG_RCMGR environment variable?

Sure! Is it a boolean value? Not a coder, sorry. )

**Comment by marten-seemann** [comment]
`LOTUS_DEBUG_RCMGR=1`

**Comment by j1v** [comment]
I did a quick search and found : 

`if os.Getenv("LOTUS_DEBUG_RCMGR") != "" {`

and decided it just has to be nonempty. 

I did restart this morning with  `LOTUS_DEBUG_RCMGR=TRUE` and this is the only occurrence of the error since in the log. 

lotusmarkets@filecoin:~$ grep -a 2022-05-12T12:21 /var/log/lotus/markets.log
2022-05-12T12:21:20.035+0300	INFO	net/identify	identify/id.go:364	failed negotiate identify protocol with peer	{"peer": "12D3KooWLJyWUESy82HFvizBhNwqxNQ8jg4vuG1fJaKjmBKgDXDu", "error": "stream reset"}
2022-05-12T12:21:31.127+0300	WARN	rcmgr	go-libp2p-resource-manager@v0.2.1/scope.go:102	BUG: too much memory released
2022-05-12T12:21:36.907+0300	INFO	net/identify	identify/id.go:364	failed negotiate identify protocol with peer	{"peer": "12D3KooWFaNacHBP1jhi2HsNYJNrH3WnECufzbtW46ko2x8KPZpN", "error": "stream reset"}

I don't see anything more detailed as log. 

Should I restart again with `=1`

**Comment by Shekelme** [comment]
With this envar set I don't see that message (BUG: too much memory released).

**Comment by j1v** [comment]
in my node it happened again a couple of hours after the restart. I think it's more network/peer , than node related ...

**Comment by marten-seemann** [comment]
It should create a log file `rcmgr.json.gz`.

**Comment by j1v** [comment]
Where ?

**Comment by j1v** [comment]
Found it - 37MB so far. How and where to send it or should I  just unzip / extract the logs around `2022-05-12T12:21:31` ?

**Comment by marten-seemann** [comment]
Post the entire file here please.

**Comment by j1v** [comment]
I think it's not allowed.

**Comment by Shekelme** [comment]
[rcmgr.json.gz](https://github.com/filecoin-project/lotus/files/8679062/rcmgr.json.gz)

**Comment by Trevor-K-Smith** [comment]
Experiencing this issue as well.

```
filecoin@Miner-01:~$ lotus-miner version
Daemon:  1.15.2+mainnet+git.518dc962e+api1.5.0
Local: lotus-miner version 1.15.2+mainnet+git.518dc962e
```

**Comment by marten-seemann** [comment]
Is there any way to reproduce this?
