### ISSUE TITLE
CommittedCapacitySectorLifetime is slightly off

### ISSUE THREAD

**Issue by jamerduhgamer** [filecoin-project/lotus#8639]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus --version
lotus version 1.15.2+mainnet+git.518dc962e

lotus-miner --version
lotus-miner version 1.15.2+mainnet+git.518dc962e
```

### Describe the Bug

Setting the CommittedCapacitySectorlifetime = "4320h0m0s" in the config.toml file results in sectors that are longer than 180 days. The lotus-miner has also been restarted since setting the configuration.

### Logging Information

```text
lotus-miner sectors list

33912  Proving  YES      NO      2404588 (in 30 weeks 19 hours)    CC
33914  Proving  YES      NO      2404597 (in 30 weeks 19 hours)    CC

cat .lotusminer/config.toml | grep Committed
  # CommittedCapacitySectorLifetime is the duration a Committed Capacity (CC) sector will
  CommittedCapacitySectorLifetime = "4320h0m0s"
```

### Repo Steps

1. Set CommittedCapacitySectorLifetime = "4320h0m0s" in the .lotusminer/config.toml file.
2. Run 'lotus-miner run'
3. Do 'lotus-miner sectors pledge' and let sector finish sealing
4. See 'lotus-miner sectors list --states Proving' and the Expiration field will be >25 weeks and 5 days. Actually shows 30 weeks for brand new sectors.

**Comment by rjan90** [comment]
Hey @jamerduhgamer!

Thanks for the issue report. We are aware of this issue and are tracking it here #7609! The underlying issue is that the MaxProveCommitDuration-buffer is taken into account in the creation of the CC-sector. Some initial work on the issue where started last week afaik.

I will close, but reference this, in the issue that we are already actively tracking - but would like to discuss/get some thoughts around how we can surface the issues we are actively tracking better to the community if you have some! So we don´t so easily end up in situation where time is spent on creating duplicates. Feel free to reach out to me on Slack if you have some ideas, or post them here. Initial thinking is display our issue-tracking board even more publicly maybe 🤔 .

**Comment by stuberman** [comment]
Having an issues list of issues that are being worked on and prioritized would help us understand. 
Right now there are 500 open Lotus issues (and we also work on others repos such as Boost) and many of those sit dormant often being closed after time. 

The reason this issue is high priority for us is we use the minimal CC duration for ESPA and this forces the accelerator to run an extra month while sectors are still active and proving.

**Comment by rjan90** [comment]
> Right now there are 500 open Lotus issues (and we also work on others repos such as Boost) and many of those sit dormant often being closed after time.

Agree! # of issues is not sustainable and has not been sustainable for while - for everybody in the ecosystem. We are actively trying to get the # down by triaging, reproducing, and closing as many **unvalid** issues, while trying our best to **keep valid issues** open (not closing issues that should have been open).

That said, there has been little control over what gets posted as an issue, and we will most likely have to create some better checks for information / context / repro-steps (where possible) before we accept them as issues and send them to the developers to look at. This issue was very well written 👍 and is a standard that we would really like to see. Ideally, the turn-around time from issue to fix will get lower with that.

I will try to think about some ways that we can better highlight and show what issues we are currently working on. 

> The reason this issue is high priority for us is we use the minimal CC duration for ESPA and this forces the accelerator to run an extra month while sectors are still active and proving.

Understand, and I agree that it should be fixed, especially since the specs describes 180 days. I will see if I can bring some more clarity to what to progress on it is, and what is potentially blocking a fix!

**Comment by Jasmine456** [comment]
I also met the same problem, may I ask if there is a solution to this problem now  
@rjan90
