### ISSUE TITLE
v1.15.2+ proof validation failed, sector not found in sector set after cron: sector not found

### ISSUE THREAD

**Issue by lanpin** [filecoin-project/lotus#8747]
https://github.com/filecoin-project/lotus/issues/3355
AND
https://github.com/filecoin-project/lotus/issues/8694

lotus-miner version 1.15.2+mainnet+git.a5792c5dc.dirty
this problem reproduces
------------------------------------
Manually changing the state of the sector to "FinalizeSector" can temporarily solve this problem.
```bash
lotus-miner sectors update-state --really-do-it [sectorId] FinalizeSector
```
if your config "FinalizeEarly = true", you need:
```bash
lotus-miner sectors update-state --really-do-it [sectorId] CommitFinalize
```
It resends the ProveCommitSector message to fix this.

**Comment by Reiers** [comment]
Hi @lanpin 

Thanks for the report. Looks like you are running Lotus with custom code or adjustment .`dirty`

Please upgrade to stock lotus, `make clean all` !
If the issue persist - leave a comment on here with new logs and repro steps. 

Thank you !

**Comment by lanpin** [comment]
@Reiers 
I'm sure the issue is not related to custom code
It may be related to the parameter "CollateralFromMinerBalance".
My miner's available balance is insufficient, and the collateral in the on-chain message will make up for it. Does this cause verification failure?

**Comment by lanpin** [comment]
@Reiers 
I found some useful information, but I can't make it public, how can I share it with you?

**Comment by marco-storswift** [comment]
It may be related to the parameter "CollateralFromMinerBalance". miner's available balance is insufficient.
I got the same issue.  I used lotus-miner sectors update-state --really-do-it [sectorId] CommitFinalize to fix this,  I check the sectors status,  the last provecommit message is on the chain , why need to resend this mesage?

**Comment by Reiers** [comment]
Hi 

Thanks for the report. The issue is outdated and both issues mention is closed. 

If this is a issue in the current release - please open a new ticket.

As for the message needs that needs to be sent again  - please open a new ticket with logs from the sector @marco-storswift 

Thank you !

**Comment by cerblue** [comment]
This happens when miner's unlocked balance was enough to cover pledge collateral when ProveCommit was sent but drops below before ConfirmSectorProofsValid is sent to miner actor from storage power actor's cron tick task ([code](https://github.com/filecoin-project/specs-actors/blob/d56b240af24517443ce1f8abfbdab7cb22d331f1/actors/builtin/power/power_actor.go#L454)). ConfirmSectorProofsValid tries to lock up miner's unlocked balance as pledge collateral, and it fails when it's insufficient ([code](https://github.com/filecoin-project/specs-actors/blob/3c87d38a4829460c92a084465521f649d7613796/actors/builtin/miner/miner_actor.go#L1184)). The power actor swallows this error ([code](https://github.com/filecoin-project/specs-actors/blob/d56b240af24517443ce1f8abfbdab7cb22d331f1/actors/builtin/power/power_actor.go#L466)), and the sector never becomes valid. The miner waits indefinitely with the error message.

Putting the sector in some state to re-send ProveCommit message pulls the sector out of this state, as it'll make the power actor to send ConfirmSectorProofsValid to miner actor again. If the miner balance is sufficient this time, the sector becomes valid.
