### ISSUE TITLE
Standalone sealing manager process

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#8790]
Currently the sealing manager is part of the lotus-miner process. We should make it possible to extract that component into a separate process
* Make it possible to use one pool of storage/workers for multiple miner actors, with potentially different sector sizes and even on different networks
* Move closer to an architecture where the storage index/worker scheduling can run redundantly.

**Comment by jennijuju** [comment]
updated the effort to weeks to reflect the testing + pr review/fix time

**Comment by benjaminh83** [comment]
This is an awesome feature. 
We would love to test this on a large scale system. We have a 15TiB/day sealing cluster and multiple calib miners connected. Let us know if something is landing!

**Comment by Fatman13** [comment]
https://github.com/ipfs-force-community/venus-cluster has successfully moved the changing of state machine of sealing sectors to worker and has been adopted by SPs large and small on mainnet since earlier this year.

I am wondering if Lotus could just adopt `venus-cluster` directly as part of its sealing pipeline for PoReps?
