### ISSUE TITLE
Sector index redundancy

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#8791]
Related to https://github.com/filecoin-project/lotus/issues/8790

Lotus sector storage subsystem has a [sector index](https://github.com/filecoin-project/lotus/blob/master/extern/sector-storage/stores/index.go#L30) which is responsible for tracking on which storage sectors live, and where sectors live / can be allocated.

Right now this is backed by a non-persistent in-memory maps, running inside the main lotus-miner process. This is good-enough for now, but after we land changes like the [standalone sealing process](https://github.com/filecoin-project/lotus/issues/8790), and have more potential future improvements (multiple/redundant worker pools, redundant proving processes), we may need to make this component more robust.

Possible solutions would be:
* Adding some local-consensus, like raft, to the existing lotus sector index, making it multi-process
* Implementing a sector index backed by a robust database like postgres / redis.

**Comment by rjan90** [comment]
This ticket was initially created to explore how to implement sector index redundancy for the Lotus-Miner. Due to the architectural challenges of Lotus-Miner, especially for large-scale users (see: [GitHub Discussion](https://github.com/filecoin-project/lotus/discussions/9686)), this issue was not addressed within the Lotus-Miner itself.

The insights and feedback from this ticket contributed to the development of Curio, which successfully addresses the sector index redundancy problem. For more information, see the Curio documentation.

Since there are no plans to implement this feature in Lotus-Miner, and because the Curio codebase has been moved out of this repository, I will close this ticke
