### ISSUE TITLE
Unregister worker on the miner before shutting down worker

### ISSUE THREAD

**Issue by SBudo** [filecoin-project/lotus#8869]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

When shutting down a worker, the miner continuously checks the connection and logs an error in the log every 5 seconds.
We frequently move workers in and out between miners, between mainnet and testnet, etc.
The only way for the miner to stop checking this specific worker, is to restart the miner, which is not ideal and often very hard to do on larger scale servers. 

### Describe the solution you'd like

In the same way as we register a worker to the miner, it would be great to have a "unregister" command on the worker or on the miner that would inform the miner that the worker is no longer available and gone offline.

### Describe alternatives you've considered

No alternative expect restarting the miner.

**Comment by rjan90** [comment]
Hey @SBudo! Thanks for the feature-request, there is also at least one other issue/feature-request open about this feature: #7570, and I do see that its a bit problematic seeing the error logged every 5 seconds.

I will raise this feature request with the devs, and hear if there is something blocking making such a feature. I´ll come back with some information later.

**Comment by kyle-parkinson** [comment]
+1 to this. we have this problem.

**Comment by rjan90** [comment]
Hey @SBudo! With the new `lotus-worker stop` command (https://github.com/filecoin-project/lotus/pull/9101) the worker will get unregistered on the `lotus-miner` which will stop the spamming logs checking the connection to the worker every 5 second.

There are still some enhancements left to be made, like adding an API: https://github.com/filecoin-project/lotus/issues/9132. And also making sure that it does not try to get the storage stats from the disconnected worker when running `lotus-miner storage list`. But since we are tracking these in other issues, I´m closing this issue now!

Thank you so much for the issue report!
