### ISSUE TITLE
`spread` storage path assigning logic

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#9075]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Storage Providers that are looking to onboard a lot of data in a short time period needs to think about how, and which mount points the sealed and unsealed sectors gets assigned and stored in. Currently, a user can adjust the weight assigned to a storage path to make it more or less likely to get picked, but that operation is inconvenient and quite manual. 

When onboarding double and triple digits of TiB per day spreading and balancing that load out over xx-mount points is quite crucial to not overload a single mountpoint.

### Describe the solution you'd like

Similar to the `spread` [worker assigning logic](https://github.com/filecoin-project/lotus/pull/8700), it would be useful to have a similar option for storage, i.e an option to ignore storage utilization and assign sectors to as many storage paths as possible.

### Describe alternatives you've considered

- Another option would be to force the storage path picking to run through a set list of storage paths, and only stop allocation to a single path if it meets the upper limit set in `"MaxStorage": 0,` in the `<path-to-storage>/sectorstorage.json` file.

**Comment by hyunmoon** [comment]
I see that this can be useful when a SP has several mount points with varying available size.
I remember having to fallocate some large dummy files to even out the space left among mount points.
(But in the end, it's a bit of moot unless the leftover space won't be utilized.)
Choosing the mount point with the most space available actually 'spreads' out the load but the problem is, depending on how fast a SP is sealing, a few to a dozen sectors would be crammed into a single mount point until lotus-miner recognizes that the mount point no longer the one with the most available space.
A proper 'spread' algorithm should mitigate the need for a higher network bandwidth per mount points.

**Comment by hyunmoon** [comment]
I see that this can be useful when a SP has several mount points with varying available sizes.
First, I remember having to 'fallocate' some large dummy files to even out space left among mount points.
(But in the end, it was a bit of moot unless the leftover space won't be utilized.)
Second, the current method that's selecting the mount point with the most leftover space actually spreads out the load but the problem is, depending on how fast a SP is sealing, a few to a dozen sectors could be crammed into a single mount point until lotus-miner recognizes enough reduction in leftover space, keeping mount points congested.
A proper 'spread' algorithm should mitigate the need for a complicated block storage solution or a higher network bandwidth per mount point.

**Comment by hyunmoon** [comment]
I see that this can be useful when a SP has several mount points with varying available sizes.
I used to 'fallocate' some large dummy files to even out space left among mount points.
(But in the end, it was a bit of moot unless the leftover space won't be utilized.)
Also, the current method that's selecting the mount point with the most leftover space actually spreads out the load but the problem is, depending on how fast a SP is sealing, a few to a dozen sectors could be crammed into a single mount point until lotus-miner recognizes enough reduction in leftover space, keeping mount points congested.
A proper 'spread' algorithm should mitigate the need for a complicated block storage solution or a higher network bandwidth per mount point.

**Comment by hyunmoon** [comment]
The current method actually spreads out the load but depending on how fast a SP is sealing, a few to a dozen sectors would be crammed into a single mount point until lotus-miner recognizes enough reduction in leftover space, keeping mount points congested.
A proper 'spread' algorithm should mitigate the need for a block storage solution or a higher bandwidth per mount point.

**Comment by magik6k** [comment]
This makes sense, and I'd propose that the `spread` logic for paths would still take weight into account, just ignore available space when comparing paths.

> can't that be achieved with spread on tasks and properly attaching storage locations?

That assumes a single path per worker, right? If I add a new array to a storage box, and want it to be attached as a separate path, I'd need to start a new worker.

**Comment by benjaminh83** [comment]
> That assumes a single path per worker, right? If I add a new array to a storage box, and want it to be attached as a separate path, I'd need to start a new worker.

That is actually what I have been running in my test setup. 2 workers for each path - so I have 4 workers on a server that holds 2 paths. That might be quite excessive, as we only needed 2 workers for redundancy, and having multiple paths in a lotus-worker should be fine? 

Thinking more about it - our scaling bottleneck will be write operations per array (and normally one array would be one path). **So ideally, lotus should do a fixed round-robin on all paths, and not think about worker resources or capacity, until the max limit is hit.** This "dumb" round robin on a list of paths, is the best way to make sure we have the longest period of time before the same path will be hit with yet another write request.

**Comment by rjan90** [comment]
Closing this as completed by #10356, as these new experimental assingers spreads the sectors better.
