### ISSUE TITLE
Add GetBeneficiaryandTerm API

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9256]
https://github.com/filecoin-project/builtin-actors/blob/b7ad2c55363c363f61275ca45ef255e28f305254/actors/miner/src/lib.rs#L3467

https://github.com/filecoin-project/builtin-actors/blob/b7ad2c55363c363f61275ca45ef255e28f305254/actors/miner/src/state.rs#L1261

technically we can separate those - but i feel like its a better UI to get all beneficiary info by one call

**Comment by arajasek** [comment]
I'm still not thrilled about continuing to add API accessors for new information. Can we consider lowering this to P3 / polling for how much this is desired by users? It'd be easy enough to add at any time.

Without this, folks can still access the information in question using `StateReadState`.

**Comment by jennijuju** [comment]
I will lower it for this time - but then would love to understand when an API can be added to lotus.

**Comment by arajasek** [comment]
Let's try to find an answer to the question. From my perspective, we want the Lotus API to provide the functionality needed by its clients. This primarily includes:

- functionality needed by the miner (the predominant client of the Lotus API). This is why we have such odd things as `MinerGetBaseInfo` and `SyncSubmitBlock` in here.
- functionality needed by "casual" clients. This is mostly simple accessors like `ChainGetBlock`, and methods that benefit from a Lotus node's connection to its peers like `MpoolPushMessage`.

I don't think it's very useful to have methods that manipulate a particular actor in a specific way be exposed over the API. I have a hard time imagining why someone would want a remote Lotus node somewhere to create, sign, and push a message that changes a specific miner's benificiary address from X to Y. Why is the key in question on some remote machine? Why wouldn't the user of this message just form the message themselves, instead of asking a remote Lotus node to do it for them?

I'm sure _some_ use case exists for this, but that's not the bar I think we should set for adding methods to the API. There _is_ a maintenance and cleanness cost to adding methods, so some circumspection seems advisable.

**Comment by jennijuju** [comment]
@magik6k suggested to fold it into GetMinerInfo
