### ISSUE TITLE
add caller for actorWithdrawCmd

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9258]
`actorWithdrawCmd` should now take a from address

`lotus-miner actor withdraw <actor>  <caller address>`

the cmd should only proceed if the caller is the owner or beneficiary of the actor

**Comment by geoff-vball** [comment]
Implemented in https://github.com/filecoin-project/lotus/pull/9296

actorWithdrawCmd now takes an optional --beneficiary flag to send the message from the beneficiary address. No need for a `--from` flag here because there are only two possible senders.

I will add a `--actor` flag to this command so we can specify which miner to send the message to.

**Comment by jennijuju** [comment]
> just to get that right - if a beneficiary address is set and i send the message from the owner - the owner gets the funds?

Nope. According to the fip it’s always to beneficiary.
