### ISSUE TITLE
FIP-0045 update sector extension  

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9369]
see https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0045.md#sector-extension 

update sectors renew/ extend

needs to  be at least cur_epoch - sector_end_epoch ≤ 30 * epoch day

(sector expiration - sector activation) → sector duration upto term max (duration)

**Comment by jennijuju** [comment]
(sector extension for new deals shouldn't happen any time soon, so this may  be done post upgrade in a feature release

**Comment by geoff-vball** [comment]
Note: This 30-day restriction only applies if you are **dropping verified deals** from the sectors.

**Comment by jennijuju** [comment]
ExtendSectorExpiration2 can be used for all sectors

**Comment by arajasek** [comment]
Okay, here's what I would propose we do:

**Milestone 1**

- Start using the new `ExpirationExtension2` type
- Add a new `--drop-claims` bool. If true, we will _consider_ dropping claims in order to extend sectors.
- No changes to the logic deciding _which_ sectors to extend, or _what_ the new expiration should be
- When [preparing the extension message](https://github.com/filecoin-project/lotus/blob/6028d7ba1882aa82dad6a61630f9fb7c91e0ff73/cmd/lotus-miner/sectors.go#L1059-L1093):
  - If a sector is a CC sector, add to the [sectors Bitfield](https://github.com/filecoin-project/builtin-actors/blob/4db0f1fd4a92a758b9a0d63c59c3634011319077/actors/miner/src/types.rs#L164)
  - If a sector has a claim that CAN be extended to _the chosen extension epoch_, add it to [maintain_claims](https://github.com/filecoin-project/builtin-actors/blob/4db0f1fd4a92a758b9a0d63c59c3634011319077/actors/miner/src/types.rs#L164) for that `SectorClaim`
  - If a sector has a claim that CANNOT be extended to _the chosen extension epoch_, and `--drop-claims` was NOT set to true, log that the sector is not being extended, and don't extend that sector
  - If a sector has a claim that CANNOT be extended to _the chosen extension epoch_, and `--drop-claims` was set to true, AND the sector can be dropped [according to the rules of FIP-0045](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0045.md#sector-extension), add it to [drop_claims](https://github.com/filecoin-project/builtin-actors/blob/4db0f1fd4a92a758b9a0d63c59c3634011319077/actors/miner/src/types.rs#L156) for that `SectorClaim`

**Milestone 2**

- Calculate the best possible epoch for a sector with claims
- This is fairly non-trivial, because it becomes a balancing decision -- depending on the definition of "best", it might make sense to drop _some_ claims while maintaining others

**Comment by ZenGround0** [comment]
> If a sector has a claim that CANNOT be extended to the chosen extension epoch, and --drop-claims was NOT set to true, log that the sector is not being extended, and don't extend that sector

And being overly pedantic this also applies if the claim CANNOT be extended and --drop-claims is set to true but the sector can't be dropped i.e. because we're not yet in the 30 day drop window.
