### ISSUE TITLE
Dramatic changes in estimated gaspremium  value

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/lotus#9470]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

The figure below shows the sampling between 2236115 and 2236122 epoch , and the gaspremium increase from 6361145 to 204424985,  gaspremium rises very fast. gasprium increase 30x within 10 blocks,  this hurts the stability of network. 

![image](https://user-images.githubusercontent.com/41407352/195267925-7a87add0-fefa-4a12-8c60-b11805a30994.png)

current algorithm @Kubuxu 

```
What the estimation function does is it looks at: "What is the expected gas premium I have to pay to get into the next N blocks" (assuming that FeeCap and base fee allow for that).

Today it takes 2*N blocks, collects messages from these blocks, sorts them by GasPremium in descending order and then looks at the GasPremium of a message which is at 0.55*2*N*BlockGasTarget counting by gas from the top of that list, so the percentile is by gas
```

**Comment by hunjixin** [comment]
this is the result I got from analyzing the block messages when the problem occurred. The miner f01852677 set the value of gaspremium above 200 million, when he sent the ProveCommitAggregate continuously,  each message's gaslimit is about 1.6 billion, there will be some messages with high gaslimit and gaspremium,  and after these messages were packed, the value of gaspremium would be predicted to rise rapidly.

**Comment by hunjixin** [comment]
![image](https://user-images.githubusercontent.com/41407352/195282419-66fbeaa9-dba5-4aa3-bf7a-79bdf63fe45e.png)

**Comment by Kubuxu** [comment]
I would call it an expected behaviour of this system. Block space is limited, BaseFee achieves the primary balance; it would be interesting to see the BaseFee during this period. We should see an increasing BaseFee.

When multiple messages are willing to pay the same BaseFee (by setting the FeeCap), SPs sort messages by the expected return, for which the primary factor is GasPremium, FeeCap and BaseFee.
The message never will pay more than FeeCap per unit of gas, GasPremium is how much the message is willing to offer to the SP per unit of gas, but GasPremium+BaseFee cannot be greater than FeeCap. Therefore, the GasPremium will be reduced, and the SP will pay a penalty equivalent to the difference if it is reduced below zero.
BaseFee during that period was around 0.1-0.7nFIL, equivalent to 100,000,000 to 700,000,000.

Another interesting metric would be the distribution of GasPremiums of messages included in that period, caveat here is that some low premium messages might have been included due to message chains, where a follow-up message pays the GasPremium for a previous message.
